export const drcLocations: string[] = [
  // Kinshasa - Communes
  'Bandalungwa', 'Barumbu', 'Bumbu', 'Gombe', 'Kalamu', 'Kasa-Vubu',
  'Kimbanseke', 'Kinshasa', 'Kintambo', 'Kisenso', 'Lemba', 'Limete',
  'Lingwala', 'Makala', 'Maluku', 'Masina', 'Matete', 'Mont-Ngafula',
  'Ndjili', 'Ngaba', 'Ngaliema', 'Ngiri-Ngiri', 'Nsele', 'Selembao',
  // Grandes villes
  'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu',
  'Goma', 'Tshikapa', 'Kolwezi', 'Likasi', 'Kikwit', 'Uvira',
  'Bunia', 'Kalemie', 'Matadi', 'Kabinda', 'Butembo', 'Beni',
  'Mwene-Ditu', 'Isiro', 'Kindu', 'Boma', 'Bandundu', 'Gbadolite',
  'Gemena', 'Lisala', 'Mbandaka', 'Lodja', 'Kipushi', 'Ilebo',
  'Fungurume', 'Kamina', 'Manono', 'Sake', 'Mongbwalu', 'Zongo',
  'Kenge', 'Gandajika', 'Lusambo', 'Bumba', 'Watsa', 'Kasumbalesa',
  'Tshilenge', 'Kongolo', 'Mweka', 'Basankusu', 'Boende', 'Inongo',
  'Nioki', 'Mushie', 'Dekese', 'Demba', 'Luebo', 'Dimbelenge',
  'Kabalo', 'Lubao', 'Mitwaba', 'Pweto', 'Dilolo', 'Kapanga',
  'Sandoa', 'Mutshatsha', 'Kaniama', 'Kabongo', 'Malemba-Nkulu',
  'Moba', 'Nyunzu', 'Fizi', 'Baraka', 'Kabare', 'Kalehe',
  'Idjwi', 'Shabunda', 'Mwenga', 'Walungu', 'Masisi', 'Rutshuru',
  'Walikale', 'Lubero', 'Bafwasende', 'Mambasa', 'Irumu', 'Djugu',
  'Mahagi', 'Aru', 'Faradje', 'Dungu', 'Wamba', 'Ango',
  'Poko', 'Rungu', 'Niangara', 'Aketi', 'Buta', 'Titule',
  'Bosobolo', 'Mobayi-Mbongo', 'Yakoma', 'Businga', 'Bongandanga',
  'Befale', 'Bikoro', 'Lukolela', 'Kutu',
  // Diaspora
  'Paris', 'Bruxelles', 'Londres', 'Johannesburg', 'Nairobi',
  'Lagos', 'Kigali', 'Kampala', 'Dar es Salaam', 'Lusaka',
  'Luanda', 'Brazzaville', 'Pointe-Noire', 'Douala', 'Yaound\u00e9',
  'Abidjan', 'Dakar', 'Montr\u00e9al', 'Ottawa', 'New York',
  'Washington', 'Houston', 'Atlanta', 'Dallas', 'Chicago',
  'Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Kristiansand',
  'Li\u00e8ge', 'Anvers', 'Charleroi', 'Namur', 'Gand',
  'Lyon', 'Marseille', 'Toulouse', 'Strasbourg', 'Lille',
  'Berlin', 'Munich', 'Francfort', 'Hambourg', 'Cologne',
  'Gen\u00e8ve', 'Z\u00fcrich', 'Lausanne', 'B\u00e2le', 'Berne',
  'Manchester', 'Birmingham', 'Glasgow', 'Leeds', 'Bristol',
  'Le Cap', 'Pretoria', 'Durban', 'Maputo', 'Harare',
];
