import { successResponse, errorResponse, authenticateAdmin } from '../../../_lib/helpers';
import { getPool } from '../../../_lib/db';

// [category, question, options_json, correct_answer_index, difficulty]
type Q = [string, string, string, number, string];

const QUESTIONS: Q[] = [
  // ===================== CULTURE (43 questions) =====================
  ['Culture', 'Quel romancier nigérian a écrit "Things Fall Apart" (Le monde s\'effondre) en 1958 ?', '["Wole Soyinka", "Chinua Achebe", "Ben Okri", "Chimamanda Ngozi Adichie"]', 1, 'medium'],
  ['Culture', 'Quel peintre espagnol a réalisé le tableau "Guernica" en 1937 ?', '["Salvador Dalí", "Joan Miró", "Pablo Picasso", "Francisco Goya"]', 2, 'medium'],
  ['Culture', 'Quel est le nom du mouvement littéraire fondé par Aimé Césaire, Léon-Gontran Damas et Léopold Sédar Senghor ?', '["Le Surréalisme", "La Négritude", "Le Réalisme magique", "Le Panafricanisme littéraire"]', 1, 'hard'],
  ['Culture', 'Quel sculpteur sénégalais a créé le Monument de la Renaissance africaine à Dakar ?', '["Ousmane Sow", "Pierre Goudiaby Atepa", "El Hadji Sy", "Iba Ndiaye"]', 1, 'hard'],
  ['Culture', 'Quel musicien malien est surnommé "le roi de la kora" ?', '["Ali Farka Touré", "Toumani Diabaté", "Salif Keita", "Habib Koité"]', 1, 'hard'],
  ['Culture', 'Quel réalisateur sénégalais est considéré comme le "père du cinéma africain" ?', '["Djibril Diop Mambéty", "Ousmane Sembène", "Souleymane Cissé", "Med Hondo"]', 1, 'hard'],
  ['Culture', 'Quelle est la forme d\'art traditionnelle japonaise consistant à plier du papier ?', '["Ikebana", "Origami", "Bonsaï", "Kintsugi"]', 1, 'easy'],
  ['Culture', 'Quel compositeur autrichien a écrit "La Flûte enchantée" ?', '["Ludwig van Beethoven", "Franz Schubert", "Wolfgang Amadeus Mozart", "Joseph Haydn"]', 2, 'medium'],
  ['Culture', 'Quel écrivain congolais (RDC) a remporté le prix Renaudot en 2012 pour "Mémoire de porc-épic" ?', '["Alain Mabanckou", "In Koli Jean Bofane", "Sony Labou Tansi", "Emmanuel Dongala"]', 0, 'hard'],
  ['Culture', 'Quel style musical né à Kinshasa dans les années 1950 est caractérisé par la guitare électrique et les rythmes cubains ?', '["Soukous", "Ndombolo", "Afrobeat", "Highlife"]', 0, 'hard'],
  ['Culture', 'Quel peintre néerlandais a peint "La Ronde de nuit" en 1642 ?', '["Johannes Vermeer", "Rembrandt van Rijn", "Frans Hals", "Pieter de Hooch"]', 1, 'hard'],
  ['Culture', 'Quel roman de Gabriel García Márquez est considéré comme le chef-d\'oeuvre du réalisme magique ?', '["L\'Amour aux temps du choléra", "Cent ans de solitude", "Chronique d\'une mort annoncée", "L\'Automne du patriarche"]', 1, 'hard'],
  ['Culture', 'Quel dramaturge norvégien est l\'auteur de "Maison de poupée" (1879) ?', '["August Strindberg", "Henrik Ibsen", "Knut Hamsun", "Bjornstjerne Bjornson"]', 1, 'hard'],
  ['Culture', 'Quel festival de cinéma africain se tient tous les deux ans à Ouagadougou, au Burkina Faso ?', '["FESPACO", "JCC", "Durban Film Festival", "Écrans Noirs"]', 0, 'hard'],
  ['Culture', 'Quel artiste américain est le pionnier du mouvement pop art avec ses sérigraphies de boîtes de soupe Campbell ?', '["Roy Lichtenstein", "Andy Warhol", "Jasper Johns", "Robert Rauschenberg"]', 1, 'medium'],
  ['Culture', 'Quel est le nom de la danse traditionnelle argentine née dans les faubourgs de Buenos Aires ?', '["Salsa", "Cumbia", "Tango", "Merengue"]', 2, 'easy'],
  ['Culture', 'Quel écrivain français a écrit "Les Misérables" ?', '["Émile Zola", "Gustave Flaubert", "Victor Hugo", "Alexandre Dumas"]', 2, 'easy'],
  ['Culture', 'Quel musicien nigérian a créé le genre Afrobeat dans les années 1970 ?', '["King Sunny Ade", "Fela Kuti", "Ebenezer Obey", "Burna Boy"]', 1, 'hard'],
  ['Culture', 'Quelle oeuvre de Léonard de Vinci représente le dernier repas de Jésus avec ses apôtres ?', '["La Joconde", "L\'Homme de Vitruve", "La Cène", "La Vierge aux rochers"]', 2, 'hard'],
  ['Culture', 'Quel écrivain kenyan a écrit en kikuyu et en anglais, notamment "Décoloniser l\'esprit" ?', '["Ngũgĩ wa Thiong\'o", "Meja Mwangi", "Grace Ogot", "Binyavanga Wainaina"]', 0, 'hard'],
  ['Culture', 'Quel courant artistique du début du XXe siècle, mené par Braque et Picasso, décompose les formes en géométrie ?', '["Fauvisme", "Cubisme", "Impressionnisme", "Expressionnisme"]', 1, 'hard'],
  ['Culture', 'Quel instrument à cordes ouest-africain, fait d\'une calebasse, possède traditionnellement 21 cordes ?', '["Balafon", "Kora", "Ngoni", "Djembé"]', 1, 'hard'],
  ['Culture', 'Quel écrivain sud-africain a reçu deux fois le prix Nobel de littérature... non, quel Sud-Africain a reçu le Nobel de littérature en 2003 ?', '["Nadine Gordimer", "J. M. Coetzee", "André Brink", "Alan Paton"]', 1, 'hard'],
  ['Culture', 'Quel genre théâtral japonais traditionnel utilise des masques et date du XIVe siècle ?', '["Kabuki", "Nô", "Bunraku", "Kyōgen"]', 1, 'hard'],
  ['Culture', 'Quel architecte espagnol a conçu la Sagrada Família à Barcelone ?', '["Santiago Calatrava", "Antoni Gaudí", "Rafael Moneo", "Ricardo Bofill"]', 1, 'medium'],
  ['Culture', 'Quel photographe malien est célèbre pour ses portraits en studio à Bamako depuis les années 1950 ?', '["Malick Sidibé", "Seydou Keïta", "Samuel Fosso", "Omar Victor Diop"]', 1, 'hard'],
  ['Culture', 'Quel roman de Mariama Bâ, publié en 1979, est un classique de la littérature africaine féministe ?', '["Une si longue lettre", "Le Baobab fou", "La Grève des bàttu", "Juletane"]', 0, 'hard'],
  ['Culture', 'Quel mouvement artistique né à Zurich en 1916 rejette la logique et valorise l\'absurde ?', '["Le Surréalisme", "Le Dadaïsme", "Le Futurisme", "Le Constructivisme"]', 1, 'hard'],
  ['Culture', 'Quel cinéaste japonais a réalisé "Les Sept Samouraïs" en 1954 ?', '["Yasujirō Ozu", "Akira Kurosawa", "Hayao Miyazaki", "Kenji Mizoguchi"]', 1, 'hard'],
  ['Culture', 'Quel musicien congolais, leader du groupe TPOK Jazz, est surnommé "Le Grand Maître" ?', '["Tabu Ley Rochereau", "Franco Luambo", "Papa Wemba", "Koffi Olomidé"]', 1, 'hard'],
  ['Culture', 'Quelle civilisation ancienne a créé les têtes colossales en pierre découvertes au Mexique ?', '["Maya", "Aztèque", "Olmèque", "Toltèque"]', 2, 'hard'],
  ['Culture', 'Quel écrivain marocain francophone a écrit "La Nuit sacrée", prix Goncourt 1987 ?', '["Driss Chraïbi", "Tahar Ben Jelloun", "Abdelhak Serhane", "Mohamed Choukri"]', 1, 'hard'],
  ['Culture', 'Quel est le nom du masque rituel utilisé dans les cérémonies du peuple Dogon au Mali ?', '["Kanaga", "Gelede", "Punu", "Kifwebe"]', 0, 'hard'],
  ['Culture', 'Quel compositeur allemand, devenu sourd, a composé sa Neuvième Symphonie avec l\'"Ode à la joie" ?', '["Johann Sebastian Bach", "Richard Wagner", "Ludwig van Beethoven", "Johannes Brahms"]', 2, 'medium'],
  ['Culture', 'Quel écrivain ivoirien a écrit "Allah n\'est pas obligé" (prix Renaudot 2000) ?', '["Bernard Dadié", "Ahmadou Kourouma", "Tanella Boni", "Jean-Marie Adiaffi"]', 1, 'hard'],
  ['Culture', 'Quel style de musique populaire éthiopien mélange funk, jazz et musique traditionnelle, né dans les années 1960 ?', '["Ethio-jazz", "Tizita", "Afrobeat", "Gnawa"]', 0, 'hard'],
  ['Culture', 'Quel peintre français est le chef de file de l\'impressionnisme avec "Impression, soleil levant" (1872) ?', '["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Camille Pissarro"]', 2, 'hard'],
  ['Culture', 'Quelle écrivaine nigériane a écrit "Americanah" et "L\'Hibiscus pourpre" ?', '["Chimamanda Ngozi Adichie", "Buchi Emecheta", "Flora Nwapa", "Sefi Atta"]', 0, 'medium'],
  ['Culture', 'Quel art martial brésilien mélange danse, acrobatie et musique, créé par les esclaves africains ?', '["Jiu-jitsu brésilien", "Capoeira", "Samba de roda", "Maracatu"]', 1, 'medium'],
  ['Culture', 'Quel cinéaste mauritanien a réalisé "Timbuktu" (2014), nommé aux Oscars ?', '["Mahamat-Saleh Haroun", "Abderrahmane Sissako", "Djibril Diop Mambéty", "Moussa Touré"]', 1, 'hard'],
  ['Culture', 'Quel est le nom du tissu coloré porté en Afrique de l\'Ouest, souvent associé au Ghana ?', '["Bogolan", "Kente", "Kitenge", "Bazin"]', 1, 'hard'],
  ['Culture', 'Quel peintre mexicain est célèbre pour ses autoportraits et son engagement politique, épouse de Diego Rivera ?', '["Leonora Carrington", "Frida Kahlo", "Remedios Varo", "María Izquierdo"]', 1, 'easy'],
  ['Culture', 'Quel écrivain et homme politique martiniquais a écrit "Cahier d\'un retour au pays natal" ?', '["Frantz Fanon", "Aimé Césaire", "Édouard Glissant", "Patrick Chamoiseau"]', 1, 'hard'],

  // ===================== ÉCONOMIE (43 questions) =====================
  ['Économie', 'Quel économiste écossais est considéré comme le père de l\'économie moderne avec "La Richesse des nations" (1776) ?', '["David Ricardo", "Adam Smith", "John Stuart Mill", "Thomas Malthus"]', 1, 'medium'],
  ['Économie', 'Quel est le nom de la monnaie commune utilisée par les pays de la zone euro ?', '["Dollar", "Livre", "Euro", "Franc"]', 2, 'easy'],
  ['Économie', 'Quel accord de libre-échange nord-américain a été remplacé par l\'ACEUM (USMCA) en 2020 ?', '["MERCOSUR", "ALENA (NAFTA)", "CARICOM", "ALBA"]', 1, 'hard'],
  ['Économie', 'Quelle institution de Bretton Woods accorde des prêts aux pays en développement pour réduire la pauvreté ?', '["FMI", "Banque mondiale", "OMC", "BRI"]', 1, 'hard'],
  ['Économie', 'Quel économiste britannique a théorisé l\'intervention de l\'État en période de crise dans sa "Théorie générale" (1936) ?', '["Friedrich Hayek", "Milton Friedman", "John Maynard Keynes", "Alfred Marshall"]', 2, 'hard'],
  ['Économie', 'Quel pays africain possède le PIB le plus élevé du continent en 2024 ?', '["Afrique du Sud", "Égypte", "Nigeria", "Algérie"]', 2, 'hard'],
  ['Économie', 'Quel est le siège de la Banque centrale européenne (BCE) ?', '["Bruxelles", "Luxembourg", "Francfort", "Paris"]', 2, 'hard'],
  ['Économie', 'Quelle organisation internationale régule le commerce mondial depuis 1995 ?', '["FMI", "CNUCED", "OMC", "OCDE"]', 2, 'medium'],
  ['Économie', 'Quel terme économique désigne une hausse générale et durable des prix ?', '["Déflation", "Stagflation", "Inflation", "Récession"]', 2, 'easy'],
  ['Économie', 'Quel est le nom de la monnaie utilisée dans la zone CEMAC (Afrique centrale) ?', '["Franc CFA (XAF)", "Naira", "Cedi", "Rand"]', 0, 'hard'],
  ['Économie', 'Quel économiste américain est le principal théoricien du monétarisme ?', '["Paul Samuelson", "Milton Friedman", "Joseph Stiglitz", "Paul Krugman"]', 1, 'hard'],
  ['Économie', 'Quel indice boursier est le principal indicateur de la Bourse de New York (NYSE) ?', '["NASDAQ", "S&P 500", "Dow Jones", "FTSE 100"]', 2, 'hard'],
  ['Économie', 'Quelle théorie économique soutient que les marchés s\'autorégulent sans intervention étatique ?', '["Keynésianisme", "Marxisme", "Libéralisme économique", "Mercantilisme"]', 2, 'hard'],
  ['Économie', 'Quel pays est le plus grand exportateur mondial de pétrole brut ?', '["États-Unis", "Russie", "Arabie saoudite", "Irak"]', 2, 'hard'],
  ['Économie', 'Quelle organisation regroupe les pays exportateurs de pétrole depuis 1960 ?', '["G7", "OPEP", "OCDE", "BRICS"]', 1, 'medium'],
  ['Économie', 'Quel économiste a formulé la théorie de l\'avantage comparatif dans le commerce international ?', '["Adam Smith", "David Ricardo", "Karl Marx", "Jean-Baptiste Say"]', 1, 'hard'],
  ['Économie', 'Quel accord a créé la Zone de libre-échange continentale africaine (ZLECAf) ?', '["Accord d\'Abuja", "Accord de Kigali", "Traité de Lagos", "Accord de Lomé"]', 1, 'hard'],
  ['Économie', 'Quel est le terme désignant le produit intérieur brut par habitant ?', '["PIB nominal", "PIB réel", "PIB par tête", "PNB"]', 2, 'medium'],
  ['Économie', 'Quelle cryptomonnaie a été créée en 2009 par le pseudonyme Satoshi Nakamoto ?', '["Ethereum", "Bitcoin", "Ripple", "Litecoin"]', 1, 'easy'],
  ['Économie', 'Quel pays asiatique a connu le "miracle économique" avec une croissance rapide après 1960, devenant un "dragon" ?', '["Thaïlande", "Philippines", "Corée du Sud", "Indonésie"]', 2, 'hard'],
  ['Économie', 'Quel est le nom de la banque centrale des États-Unis ?', '["Bank of America", "Banque fédérale de réserve (Fed)", "Trésor américain", "Wall Street Bank"]', 1, 'hard'],
  ['Économie', 'Quelle institution financière africaine, basée à Abidjan, finance le développement du continent ?', '["BAD (Banque africaine de développement)", "BCEAO", "Ecobank", "Afreximbank"]', 0, 'hard'],
  ['Économie', 'Quel économiste austro-américain a défendu la "destruction créatrice" comme moteur du capitalisme ?', '["Ludwig von Mises", "Joseph Schumpeter", "Friedrich Hayek", "Karl Polanyi"]', 1, 'hard'],
  ['Économie', 'Quel est le nom du système monétaire international mis en place à Bretton Woods en 1944 ?', '["Étalon-or", "Système de changes flottants", "Étalon dollar-or", "Système de Gênes"]', 2, 'hard'],
  ['Économie', 'Quel pays africain a adopté le dollar américain comme monnaie officielle en 2009 après une hyperinflation ?', '["Somalie", "Zimbabwe", "Soudan", "Érythrée"]', 1, 'hard'],
  ['Économie', 'Quel terme désigne une situation où l\'inflation coexiste avec une stagnation économique ?', '["Hyperinflation", "Déflation", "Stagflation", "Récession"]', 2, 'hard'],
  ['Économie', 'Quelle est la monnaie officielle du Japon ?', '["Won", "Yuan", "Yen", "Ringgit"]', 2, 'easy'],
  ['Économie', 'Quel traité de 1992 a institué l\'Union européenne et prévu la création de l\'euro ?', '["Traité de Rome", "Traité de Maastricht", "Traité de Lisbonne", "Traité de Nice"]', 1, 'hard'],
  ['Économie', 'Quel concept économique mesure la valeur de la meilleure alternative sacrifiée lors d\'un choix ?', '["Coût marginal", "Coût d\'opportunité", "Coût fixe", "Externalité"]', 1, 'hard'],
  ['Économie', 'Quel groupe de pays émergents est désigné par l\'acronyme BRICS ?', '["Brésil, Russie, Inde, Chine, Singapour", "Brésil, Russie, Inde, Chine, Afrique du Sud", "Belgique, Russie, Inde, Canada, Suisse", "Brésil, Roumanie, Indonésie, Chine, Suède"]', 1, 'medium'],
  ['Économie', 'Quel économiste a écrit "Le Capital" en 1867, critique fondamentale du capitalisme ?', '["Friedrich Engels", "Karl Marx", "Pierre-Joseph Proudhon", "Max Weber"]', 1, 'medium'],
  ['Économie', 'Quelle banque centrale émet le franc CFA pour les pays de l\'UEMOA (Afrique de l\'Ouest) ?', '["BEAC", "BCEAO", "BCRG", "BCC"]', 1, 'hard'],
  ['Économie', 'Quel phénomène économique se produit quand un pays riche en ressources naturelles connaît un déclin de ses autres secteurs ?', '["Effet de levier", "Maladie hollandaise", "Bulle spéculative", "Trappe à liquidité"]', 1, 'hard'],
  ['Économie', 'Quel pays est le premier producteur mondial de cacao ?', '["Ghana", "Côte d\'Ivoire", "Indonésie", "Nigeria"]', 1, 'hard'],
  ['Économie', 'Quel est le nom de l\'indice qui mesure le développement humain (santé, éducation, revenu) ?', '["PIB", "Indice de Gini", "IDH (Indice de développement humain)", "Indice Big Mac"]', 2, 'hard'],
  ['Économie', 'Quel accord commercial régional regroupe les pays d\'Afrique de l\'Est (Kenya, Tanzanie, Ouganda, etc.) ?', '["CEDEAO", "SADC", "EAC (Communauté d\'Afrique de l\'Est)", "COMESA"]', 2, 'hard'],
  ['Économie', 'Quel terme désigne la capacité d\'un bien à satisfaire un besoin en économie ?', '["Élasticité", "Utilité", "Rentabilité", "Productivité"]', 1, 'hard'],
  ['Économie', 'Quelle crise financière mondiale a débuté avec l\'effondrement des subprimes aux États-Unis ?', '["Crise de 1929", "Crise asiatique de 1997", "Crise de 2008", "Crise de la dette européenne"]', 2, 'medium'],
  ['Économie', 'Quel pays est le premier partenaire commercial de l\'Afrique depuis les années 2010 ?', '["États-Unis", "France", "Chine", "Inde"]', 2, 'hard'],
  ['Économie', 'Quel économiste indien a reçu le prix Nobel en 1998 pour ses travaux sur l\'économie du bien-être ?', '["Amartya Sen", "Muhammad Yunus", "Raghuram Rajan", "Abhijit Banerjee"]', 0, 'hard'],
  ['Économie', 'Quel est le principal minerai exporté par la République démocratique du Congo ?', '["Or", "Diamant", "Cobalt", "Cuivre"]', 2, 'hard'],
  ['Économie', 'Quel concept keynésien désigne l\'effet multiplicateur des dépenses publiques sur l\'économie ?', '["Effet d\'éviction", "Multiplicateur budgétaire", "Trappe à liquidité", "Paradoxe de l\'épargne"]', 1, 'hard'],
  ['Économie', 'Quelle bourse africaine, située à Johannesburg, est la plus grande du continent ?', '["Bourse de Lagos", "Bourse de Nairobi", "JSE (Johannesburg Stock Exchange)", "Bourse du Caire"]', 2, 'hard'],

  // ===================== ÉDUCATION (43 questions) =====================
  ['Éducation', 'Quelle est la plus ancienne université encore en activité dans le monde ?', '["Université de Bologne", "Université Al Quaraouiyine", "Université d\'Oxford", "Université de Paris"]', 1, 'hard'],
  ['Éducation', 'Quel pédagogue italien a développé une méthode éducative basée sur l\'autonomie de l\'enfant ?', '["Jean Piaget", "Maria Montessori", "Friedrich Fröbel", "Rudolf Steiner"]', 1, 'medium'],
  ['Éducation', 'Dans quel pays se trouve l\'université de Harvard ?', '["Royaume-Uni", "Canada", "États-Unis", "Australie"]', 2, 'easy'],
  ['Éducation', 'Quel philosophe grec est considéré comme le fondateur de l\'Académie, la première institution d\'enseignement supérieur en Occident ?', '["Socrate", "Aristote", "Platon", "Épicure"]', 2, 'hard'],
  ['Éducation', 'Quel pays scandinave est régulièrement classé premier dans les évaluations PISA pour la qualité de son système éducatif ?', '["Suède", "Norvège", "Finlande", "Danemark"]', 2, 'hard'],
  ['Éducation', 'Quel pédagogue brésilien a écrit "Pédagogie des opprimés" en 1968 ?', '["Ivan Illich", "Paulo Freire", "Augusto Boal", "Darcy Ribeiro"]', 1, 'hard'],
  ['Éducation', 'Quel est le nom du programme international d\'évaluation des élèves de 15 ans, géré par l\'OCDE ?', '["TIMSS", "PIRLS", "PISA", "SACMEQ"]', 2, 'hard'],
  ['Éducation', 'Quelle université africaine, fondée en 1827 en Sierra Leone, est la plus ancienne d\'Afrique de l\'Ouest ?', '["Université d\'Ibadan", "Université du Ghana", "Fourah Bay College", "Université de Dakar"]', 2, 'hard'],
  ['Éducation', 'Quel philosophe suisse a écrit "Émile ou De l\'éducation" en 1762 ?', '["Voltaire", "Denis Diderot", "Jean-Jacques Rousseau", "Montesquieu"]', 2, 'hard'],
  ['Éducation', 'Quel est le taux d\'alphabétisation approximatif en Afrique subsaharienne selon l\'UNESCO (2023) ?', '["45%", "55%", "65%", "75%"]', 2, 'hard'],
  ['Éducation', 'Quel système éducatif est structuré en "Grundschule" (école primaire) et "Gymnasium" (lycée) ?', '["Français", "Allemand", "Britannique", "Japonais"]', 1, 'hard'],
  ['Éducation', 'Quel pédagogue tchèque du XVIIe siècle est considéré comme le père de la pédagogie moderne avec "La Grande Didactique" ?', '["Jan Hus", "Jan Amos Comenius", "Johann Pestalozzi", "John Locke"]', 1, 'hard'],
  ['Éducation', 'Quelle organisation des Nations Unies est principalement responsable de l\'éducation dans le monde ?', '["UNICEF", "UNESCO", "PNUD", "OMS"]', 1, 'medium'],
  ['Éducation', 'Quel pays africain a introduit l\'éducation primaire gratuite et universelle en 1997, doublant ses effectifs scolaires ?', '["Kenya", "Tanzanie", "Ouganda", "Ghana"]', 2, 'hard'],
  ['Éducation', 'Quel psychologue suisse a élaboré la théorie des stades du développement cognitif chez l\'enfant ?', '["Sigmund Freud", "Jean Piaget", "Lev Vygotski", "Erik Erikson"]', 1, 'hard'],
  ['Éducation', 'Quel type d\'école coranique traditionnelle en Afrique de l\'Ouest enseigne le Coran et l\'arabe ?', '["Madrasa", "Medersa", "Daaras", "Zawiya"]', 2, 'hard'],
  ['Éducation', 'Quelle réforme éducative française de 1882, portée par Jules Ferry, a rendu l\'école primaire gratuite, laïque et obligatoire ?', '["Loi Guizot", "Lois Ferry", "Loi Falloux", "Loi Debré"]', 1, 'hard'],
  ['Éducation', 'Quel est le nom du diplôme de fin d\'études secondaires en France ?', '["Brevet", "Baccalauréat", "Licence", "Certificat d\'études"]', 1, 'easy'],
  ['Éducation', 'Quel psychologue russe a développé la théorie de la zone proximale de développement ?', '["Ivan Pavlov", "Lev Vygotski", "Alexandre Luria", "Sergueï Rubinstein"]', 1, 'hard'],
  ['Éducation', 'Quelle université, fondée au Caire en 970, est l\'un des plus anciens centres d\'enseignement islamique ?', '["Université de Timbuktu", "Université Al-Azhar", "Université de Fès", "Université de Cordoue"]', 1, 'hard'],
  ['Éducation', 'Quel pays asiatique impose un examen national très compétitif appelé "Gaokao" pour l\'entrée à l\'université ?', '["Japon", "Corée du Sud", "Chine", "Inde"]', 2, 'hard'],
  ['Éducation', 'Quel pédagogue allemand a fondé le concept de "jardin d\'enfants" (Kindergarten) en 1837 ?', '["Johann Herbart", "Friedrich Fröbel", "Rudolf Steiner", "Wilhelm von Humboldt"]', 1, 'hard'],
  ['Éducation', 'Quel est le système de notation universitaire utilisé aux États-Unis basé sur des lettres ?', '["Système décimal", "Système GPA (Grade Point Average)", "Système ECTS", "Système percentile"]', 1, 'medium'],
  ['Éducation', 'Quel philosophe américain a fondé le mouvement de l\'éducation progressive au début du XXe siècle ?', '["William James", "John Dewey", "Charles Sanders Peirce", "Ralph Waldo Emerson"]', 1, 'hard'],
  ['Éducation', 'Quelle université sud-africaine Nelson Mandela a-t-il fréquentée avant d\'être expulsé ?', '["Université du Cap", "Université de Witwatersrand", "Université de Fort Hare", "Université de Pretoria"]', 2, 'hard'],
  ['Éducation', 'Quel est le nom du système éducatif finlandais qui ne donne pas de notes avant l\'âge de 13 ans ?', '["Peruskoulu", "Gymnasium", "Folkskola", "Grundskola"]', 0, 'hard'],
  ['Éducation', 'Quel mouvement éducatif, fondé par Rudolf Steiner en 1919, met l\'accent sur la créativité et l\'imagination ?', '["Pédagogie Montessori", "Pédagogie Freinet", "Pédagogie Waldorf-Steiner", "Pédagogie Reggio Emilia"]', 2, 'hard'],
  ['Éducation', 'Quel pays a le taux d\'alphabétisation le plus élevé d\'Afrique, proche de 90% ?', '["Nigeria", "Guinée équatoriale", "Afrique du Sud", "Seychelles"]', 3, 'hard'],
  ['Éducation', 'Quel est le nom de l\'examen de fin d\'études secondaires en Allemagne ?', '["Matura", "Abitur", "A-Levels", "Baccalauréat"]', 1, 'hard'],
  ['Éducation', 'Quel pédagogue français a développé la pédagogie coopérative et le journal scolaire au XXe siècle ?', '["Célestin Freinet", "Philippe Meirieu", "Fernand Oury", "Roger Cousinet"]', 0, 'hard'],
  ['Éducation', 'Quelle initiative mondiale lancée en 2000 visait l\'éducation primaire universelle d\'ici 2015 ?', '["Éducation pour tous", "Objectifs du Millénaire pour le développement", "Agenda 2030", "Programme ERASMUS"]', 1, 'hard'],
  ['Éducation', 'Quel est le nom du système de crédits utilisé dans l\'enseignement supérieur européen depuis le processus de Bologne ?', '["GPA", "ECTS", "Credits UK", "Unités de valeur"]', 1, 'hard'],
  ['Éducation', 'Quelle militante pakistanaise, prix Nobel de la paix 2014, défend l\'éducation des filles ?', '["Benazir Bhutto", "Malala Yousafzai", "Shirin Ebadi", "Tawakkol Karman"]', 1, 'medium'],
  ['Éducation', 'Quel penseur a proposé le concept de "tabula rasa", affirmant que l\'esprit de l\'enfant est une page vierge ?', '["René Descartes", "John Locke", "David Hume", "Francis Bacon"]', 1, 'hard'],
  ['Éducation', 'Quelle est la plus ancienne université d\'Afrique francophone, fondée à Dakar en 1957 ?', '["Université de Kinshasa", "Université Cheikh Anta Diop", "Université d\'Abidjan", "Université de Yaoundé"]', 1, 'hard'],
  ['Éducation', 'Quel rapport de l\'UNESCO de 1996, dirigé par Jacques Delors, définit quatre piliers de l\'éducation ?', '["Rapport Faure", "L\'Éducation : un trésor est caché dedans", "Rapport mondial de suivi", "Déclaration de Jomtien"]', 1, 'hard'],
  ['Éducation', 'Quel système éducatif utilise les "O-Levels" et "A-Levels" comme examens de fin d\'études secondaires ?', '["Système français", "Système allemand", "Système britannique", "Système américain"]', 2, 'medium'],
  ['Éducation', 'Quel est le nom de la méthode d\'enseignement où l\'élève apprend en faisant, développée par John Dewey ?', '["Apprentissage par coeur", "Learning by doing", "Méthode socratique", "Classe inversée"]', 1, 'hard'],
  ['Éducation', 'Quel programme d\'échange universitaire européen a été lancé en 1987 ?', '["Comenius", "Erasmus", "Leonardo da Vinci", "Grundtvig"]', 1, 'medium'],
  ['Éducation', 'Quelle conférence mondiale de 1990 en Thaïlande a lancé le mouvement "Éducation pour tous" ?', '["Conférence de Dakar", "Conférence de Jomtien", "Conférence de Salamanque", "Conférence d\'Incheon"]', 1, 'hard'],
  ['Éducation', 'Quel est le nom de l\'approche pédagogique italienne née à Reggio Emilia centrée sur l\'enfant comme "chercheur" ?', '["Pédagogie Montessori", "Pédagogie Freinet", "Approche Reggio Emilia", "Pédagogie Waldorf"]', 2, 'hard'],
  ['Éducation', 'Quel pays africain a atteint un taux d\'alphabétisation de près de 100% grâce à une campagne massive en 1961 ?', '["Algérie", "Tanzanie", "Cuba", "Rwanda"]', 2, 'hard'],
  ['Éducation', 'Quel philosophe grec a fondé le Lycée et est considéré comme le précepteur d\'Alexandre le Grand ?', '["Platon", "Socrate", "Aristote", "Démocrite"]', 2, 'medium'],

  // ===================== GÉOGRAPHIE (43 questions) =====================
  ['Géographie', 'Quelle est la capitale du Burkina Faso ?', '["Bobo-Dioulasso", "Ouagadougou", "Koudougou", "Banfora"]', 1, 'medium'],
  ['Géographie', 'Quel est le plus long fleuve d\'Afrique ?', '["Congo", "Niger", "Nil", "Zambèze"]', 2, 'easy'],
  ['Géographie', 'Quelle est la capitale de la Mongolie ?', '["Almaty", "Oulan-Bator", "Bichkek", "Astana"]', 1, 'hard'],
  ['Géographie', 'Quel détroit sépare l\'Afrique de l\'Europe ?', '["Détroit de Bab-el-Mandeb", "Détroit de Gibraltar", "Détroit de Messine", "Détroit du Bosphore"]', 1, 'medium'],
  ['Géographie', 'Quel est le plus grand désert chaud du monde ?', '["Désert du Kalahari", "Désert de Gobi", "Désert du Sahara", "Désert d\'Arabie"]', 2, 'easy'],
  ['Géographie', 'Quelle est la capitale de l\'Érythrée ?', '["Djibouti", "Addis-Abeba", "Asmara", "Mogadiscio"]', 2, 'hard'],
  ['Géographie', 'Quel lac africain est le deuxième plus profond du monde après le lac Baïkal ?', '["Lac Victoria", "Lac Malawi", "Lac Tanganyika", "Lac Tchad"]', 2, 'hard'],
  ['Géographie', 'Quel pays d\'Amérique du Sud est traversé par l\'équateur et porte le nom de cette ligne imaginaire ?', '["Colombie", "Pérou", "Équateur", "Venezuela"]', 2, 'hard'],
  ['Géographie', 'Quelle chaîne de montagnes s\'étend sur toute la côte ouest de l\'Amérique du Sud ?', '["Rocheuses", "Andes", "Alpes", "Atlas"]', 1, 'medium'],
  ['Géographie', 'Quelle est la capitale du Bhoutan ?', '["Katmandou", "Thimphou", "Dacca", "Colombo"]', 1, 'hard'],
  ['Géographie', 'Quel est le plus petit pays d\'Afrique continentale par superficie ?', '["Eswatini", "Gambie", "Lesotho", "Djibouti"]', 1, 'hard'],
  ['Géographie', 'Quel fleuve traverse Kinshasa et Brazzaville ?', '["Nil", "Niger", "Congo", "Oubangui"]', 2, 'hard'],
  ['Géographie', 'Quelle île de l\'océan Indien est la quatrième plus grande île du monde ?', '["Sri Lanka", "Bornéo", "Sumatra", "Madagascar"]', 3, 'hard'],
  ['Géographie', 'Quel pays enclavé d\'Afrique australe est entièrement entouré par l\'Afrique du Sud ?', '["Eswatini", "Lesotho", "Malawi", "Botswana"]', 1, 'hard'],
  ['Géographie', 'Quel est le point culminant de l\'Afrique ?', '["Mont Kenya", "Mont Kilimandjaro", "Mont Elgon", "Ras Dashan"]', 1, 'medium'],
  ['Géographie', 'Quelle est la capitale de la Birmanie (Myanmar) ?', '["Rangoun", "Mandalay", "Naypyidaw", "Bago"]', 2, 'hard'],
  ['Géographie', 'Quel pays africain possède le plus grand nombre de lacs ?', '["RDC", "Ouganda", "Tanzanie", "Kenya"]', 1, 'hard'],
  ['Géographie', 'Quel est le fleuve le plus long d\'Asie ?', '["Mékong", "Gange", "Yangtsé (Chang Jiang)", "Ob-Irtych"]', 2, 'hard'],
  ['Géographie', 'Quelle est la capitale du Suriname ?', '["Georgetown", "Cayenne", "Paramaribo", "Belém"]', 2, 'hard'],
  ['Géographie', 'Quel pays d\'Afrique de l\'Ouest a pour capitale Niamey ?', '["Mali", "Burkina Faso", "Niger", "Tchad"]', 2, 'hard'],
  ['Géographie', 'Quel est le plus grand pays d\'Afrique par superficie ?', '["RDC", "Soudan", "Algérie", "Libye"]', 2, 'hard'],
  ['Géographie', 'Quel archipel africain situé dans l\'Atlantique a pour capitale Praia ?', '["São Tomé-et-Príncipe", "Comores", "Cap-Vert", "Seychelles"]', 2, 'hard'],
  ['Géographie', 'Quel est le nom de la faille géologique qui traverse l\'Afrique de l\'Est du Mozambique à l\'Éthiopie ?', '["Faille de San Andreas", "Rift est-africain (Grand Rift)", "Faille nord-anatolienne", "Fosse des Mariannes"]', 1, 'hard'],
  ['Géographie', 'Quelle mer intérieure est bordée par le Kazakhstan, le Turkménistan, l\'Iran, l\'Azerbaïdjan et la Russie ?', '["Mer Noire", "Mer d\'Aral", "Mer Caspienne", "Mer Rouge"]', 2, 'hard'],
  ['Géographie', 'Quel pays d\'Afrique centrale a pour capitale Libreville ?', '["Cameroun", "Congo-Brazzaville", "Gabon", "Guinée équatoriale"]', 2, 'hard'],
  ['Géographie', 'Quel est le plus haut sommet d\'Amérique du Sud ?', '["Cotopaxi", "Huascarán", "Aconcagua", "Chimborazo"]', 2, 'hard'],
  ['Géographie', 'Quelle île volcanique de l\'océan Indien est un département français et se situe près de Madagascar ?', '["Mayotte", "La Réunion", "Maurice", "Comores"]', 1, 'hard'],
  ['Géographie', 'Quel pays est traversé à la fois par le tropique du Cancer et le tropique du Capricorne... non, quel pays est traversé par l\'équateur en Afrique, baigné par l\'Atlantique et le Golfe de Guinée ?', '["Cameroun", "Gabon", "Ghana", "Guinée équatoriale"]', 1, 'hard'],
  ['Géographie', 'Quelle est la capitale de Vanuatu ?', '["Suva", "Port-Vila", "Apia", "Nuku\'alofa"]', 1, 'hard'],
  ['Géographie', 'Quel pays africain possède la plus longue côte sur l\'océan Atlantique ?', '["Afrique du Sud", "Namibie", "Somalie", "Mozambique"]', 0, 'hard'],
  ['Géographie', 'Quel fleuve d\'Afrique de l\'Ouest traverse le Mali, le Niger et le Nigeria ?', '["Sénégal", "Volta", "Niger", "Bénoué"]', 2, 'hard'],
  ['Géographie', 'Quelle est la capitale du Malawi ?', '["Blantyre", "Lilongwe", "Mzuzu", "Zomba"]', 1, 'hard'],
  ['Géographie', 'Quel est le plus grand lac d\'Afrique par superficie ?', '["Lac Tanganyika", "Lac Malawi", "Lac Victoria", "Lac Tchad"]', 2, 'medium'],
  ['Géographie', 'Quel pays d\'Asie du Sud-Est est un archipel de plus de 17 000 îles ?', '["Philippines", "Malaisie", "Indonésie", "Thaïlande"]', 2, 'hard'],
  ['Géographie', 'Quel est le nom du courant océanique chaud qui influence le climat de l\'Europe occidentale ?', '["Courant de Humboldt", "Gulf Stream", "Courant de Benguela", "Courant du Labrador"]', 1, 'hard'],
  ['Géographie', 'Quelle est la capitale du Tadjikistan ?', '["Tachkent", "Bichkek", "Douchanbé", "Achgabat"]', 2, 'hard'],
  ['Géographie', 'Quel pays africain est le seul à avoir deux capitales officielles : Yamoussoukro (politique) et Abidjan (économique) ?', '["Cameroun", "Tanzanie", "Côte d\'Ivoire", "Nigeria"]', 2, 'hard'],
  ['Géographie', 'Quel est le détroit qui sépare l\'Asie de l\'Amérique du Nord ?', '["Détroit de Malacca", "Détroit de Béring", "Détroit de Magellan", "Détroit de Torres"]', 1, 'hard'],
  ['Géographie', 'Quelle est la plus haute chute d\'eau du monde, située au Venezuela ?', '["Chutes du Niagara", "Chutes Victoria", "Salto Angel", "Chutes d\'Iguazú"]', 2, 'hard'],
  ['Géographie', 'Quel pays est le plus peuplé d\'Afrique ?', '["Éthiopie", "Égypte", "RDC", "Nigeria"]', 3, 'medium'],
  ['Géographie', 'Quelle mer intérieure salée, partagée entre Israël et la Jordanie, est le point le plus bas de la surface terrestre ?', '["Mer Rouge", "Mer Morte", "Mer d\'Aral", "Lac Assal"]', 1, 'hard'],
  ['Géographie', 'Quel volcan actif sicilien est le plus haut d\'Europe ?', '["Vésuve", "Stromboli", "Etna", "Piton de la Fournaise"]', 2, 'hard'],
  ['Géographie', 'Quelle est la capitale de l\'Eswatini (ancien Swaziland) ?', '["Maseru", "Mbabane", "Maputo", "Gaborone"]', 1, 'hard'],

  // ===================== HISTOIRE (43 questions) =====================
  ['Histoire', 'En quelle année la Conférence de Berlin a-t-elle partagé l\'Afrique entre les puissances coloniales européennes ?', '["1878", "1884-1885", "1890", "1900"]', 1, 'hard'],
  ['Histoire', 'Quel empire africain médiéval, centré sur Tombouctou, était célèbre pour sa richesse en or ?', '["Empire du Ghana", "Empire du Mali", "Empire Songhaï", "Royaume du Bénin"]', 1, 'hard'],
  ['Histoire', 'Quel leader congolais a été le premier Premier ministre de la RDC indépendante en 1960 ?', '["Mobutu Sese Seko", "Patrice Lumumba", "Joseph Kasa-Vubu", "Moise Tshombe"]', 1, 'medium'],
  ['Histoire', 'Quelle civilisation ancienne a construit les pyramides de Gizeh ?', '["Mésopotamienne", "Égyptienne", "Grecque", "Romaine"]', 1, 'easy'],
  ['Histoire', 'Quel événement a déclenché la Première Guerre mondiale en 1914 ?', '["L\'invasion de la Pologne", "L\'assassinat de l\'archiduc François-Ferdinand", "Le naufrage du Lusitania", "La révolution russe"]', 1, 'medium'],
  ['Histoire', 'Quel empereur du Mali aurait distribué tant d\'or lors de son pèlerinage à La Mecque en 1324 qu\'il a fait chuter le prix de l\'or ?', '["Soundiata Keïta", "Mansa Moussa", "Askia Mohammed", "Samori Touré"]', 1, 'hard'],
  ['Histoire', 'En quelle année le mur de Berlin est-il tombé ?', '["1987", "1989", "1991", "1993"]', 1, 'easy'],
  ['Histoire', 'Quel royaume africain précolonial, situé dans l\'actuel Bénin, était connu pour ses sculptures en bronze ?', '["Royaume du Bénin (Edo)", "Royaume d\'Oyo", "Royaume du Dahomey", "Empire Ashanti"]', 0, 'hard'],
  ['Histoire', 'Quel traité de 1919 a mis fin à la Première Guerre mondiale ?', '["Traité de Westphalie", "Traité de Versailles", "Traité de Paris", "Traité de Vienne"]', 1, 'hard'],
  ['Histoire', 'Quel leader ghanéen est considéré comme le père du panafricanisme et premier président du Ghana indépendant ?', '["Jomo Kenyatta", "Kwame Nkrumah", "Julius Nyerere", "Sékou Touré"]', 1, 'hard'],
  ['Histoire', 'Quelle révolution a renversé la monarchie française en 1789 ?', '["Révolution industrielle", "Révolution américaine", "Révolution française", "Commune de Paris"]', 2, 'easy'],
  ['Histoire', 'Quel empire a dominé la Méditerranée pendant près de cinq siècles, de la République à la chute de Rome en 476 ?', '["Empire grec", "Empire perse", "Empire romain", "Empire byzantin"]', 2, 'medium'],
  ['Histoire', 'Quel résistant algérien a mené la résistance contre la colonisation française au XIXe siècle ?', '["Ferhat Abbas", "Messali Hadj", "Abdelkader ibn Muhieddine", "Houari Boumédiène"]', 2, 'hard'],
  ['Histoire', 'En quelle année la RDC (alors Congo belge) a-t-elle obtenu son indépendance ?', '["1958", "1960", "1962", "1964"]', 1, 'medium'],
  ['Histoire', 'Quel empire ouest-africain, fondé par Soundiata Keïta au XIIIe siècle, est devenu l\'un des plus grands empires africains ?', '["Empire du Ghana", "Empire du Mali", "Empire Songhaï", "Empire du Kanem-Bornou"]', 1, 'hard'],
  ['Histoire', 'Quel événement de 1945 a marqué la fin de la Seconde Guerre mondiale en Europe ?', '["Débarquement en Normandie", "Bataille de Stalingrad", "Capitulation de l\'Allemagne nazie", "Conférence de Yalta"]', 2, 'hard'],
  ['Histoire', 'Quel navigateur portugais a atteint l\'Inde par voie maritime en 1498 ?', '["Bartolomeu Dias", "Vasco de Gama", "Ferdinand Magellan", "Christophe Colomb"]', 1, 'hard'],
  ['Histoire', 'Quelle reine du peuple Lunda a résisté à la colonisation portugaise en Angola au XVIIe siècle ?', '["Yaa Asantewaa", "Nzinga Mbandi", "Amina de Zazzau", "Nehanda Charwe"]', 1, 'hard'],
  ['Histoire', 'Quel accord de 1648 a mis fin à la Guerre de Trente Ans en Europe ?', '["Traité de Tordesillas", "Paix de Westphalie", "Traité d\'Utrecht", "Congrès de Vienne"]', 1, 'hard'],
  ['Histoire', 'Quel royaume d\'Afrique de l\'Est, fondé au XIVe siècle, a résisté à la colonisation italienne à la bataille d\'Adoua en 1896 ?', '["Royaume du Buganda", "Empire éthiopien (Abyssinie)", "Sultanat de Zanzibar", "Royaume du Rwanda"]', 1, 'hard'],
  ['Histoire', 'Quel leader sud-africain a passé 27 ans en prison avant de devenir président et de mettre fin à l\'apartheid ?', '["Desmond Tutu", "Steve Biko", "Nelson Mandela", "Walter Sisulu"]', 2, 'medium'],
  ['Histoire', 'Quel peuple a fondé la civilisation de Carthage, rivale de Rome, dans l\'actuelle Tunisie ?', '["Grecs", "Phéniciens", "Berbères", "Égyptiens"]', 1, 'hard'],
  ['Histoire', 'Quel événement de 1804 a fait d\'Haïti la première république noire indépendante ?', '["Révolution haïtienne", "Abolition de l\'esclavage en France", "Congrès de Vienne", "Guerre de Sécession"]', 0, 'hard'],
  ['Histoire', 'Quel empire d\'Afrique de l\'Ouest, fondé par Sonni Ali Ber au XVe siècle, avait pour capitale Gao ?', '["Empire du Ghana", "Empire du Mali", "Empire Songhaï", "Empire du Kanem-Bornou"]', 2, 'hard'],
  ['Histoire', 'Quelle guerre civile américaine (1861-1865) a abouti à l\'abolition de l\'esclavage ?', '["Guerre d\'Indépendance", "Guerre de Sécession", "Guerre hispano-américaine", "Guerre du Mexique"]', 1, 'hard'],
  ['Histoire', 'Quel roi du Royaume Kongo a été le premier monarque africain à établir des relations diplomatiques avec le Portugal au XVe siècle ?', '["Nzinga a Nkuwu (João I)", "Afonso I", "Garcia II", "Álvaro I"]', 0, 'hard'],
  ['Histoire', 'Quel traité de 1885 a reconnu l\'État indépendant du Congo comme propriété personnelle de Léopold II de Belgique ?', '["Acte général de la Conférence de Berlin", "Traité de Versailles", "Accord de Bruxelles", "Convention de Genève"]', 0, 'hard'],
  ['Histoire', 'Quel dirigeant a unifié la Chine en 221 av. J.-C. et fondé la dynastie Qin ?', '["Confucius", "Qin Shi Huang", "Sun Tzu", "Lao Tseu"]', 1, 'hard'],
  ['Histoire', 'Quelle bataille de 1805 a vu la victoire navale de l\'amiral Nelson contre Napoléon ?', '["Bataille de Waterloo", "Bataille d\'Austerlitz", "Bataille de Trafalgar", "Bataille de Leipzig"]', 2, 'hard'],
  ['Histoire', 'Quel mouvement de résistance kenyan des années 1950 a lutté contre la domination coloniale britannique ?', '["ANC", "Mau Mau", "FLN", "ZANU"]', 1, 'hard'],
  ['Histoire', 'En quelle année l\'Organisation de l\'Unité Africaine (OUA) a-t-elle été fondée à Addis-Abeba ?', '["1957", "1960", "1963", "1975"]', 2, 'hard'],
  ['Histoire', 'Quel conquistador espagnol a conquis l\'Empire aztèque au Mexique entre 1519 et 1521 ?', '["Francisco Pizarro", "Hernán Cortés", "Vasco Núñez de Balboa", "Pedro de Alvarado"]', 1, 'hard'],
  ['Histoire', 'Quel royaume d\'Afrique centrale, connu pour ses masques kifwebe, existait dans l\'actuel sud-est de la RDC ?', '["Royaume Kuba", "Royaume Luba", "Royaume Lunda", "Royaume Kongo"]', 1, 'hard'],
  ['Histoire', 'Quel événement de 1947 a conduit à la partition de l\'Inde britannique en deux États ?', '["Révolte des Cipayes", "Marche du sel", "Indépendance et partition de l\'Inde", "Assassinat de Gandhi"]', 2, 'hard'],
  ['Histoire', 'Quel leader tanzanien a promu le concept d\'"Ujamaa" (socialisme africain) après l\'indépendance ?', '["Jomo Kenyatta", "Milton Obote", "Julius Nyerere", "Kenneth Kaunda"]', 2, 'hard'],
  ['Histoire', 'Quelle guerre de 1899-1902, en Afrique du Sud, a opposé les Britanniques aux Boers ?', '["Guerre des Zoulous", "Guerre des Boers", "Guerre du Biafra", "Guerre de Rhodésie"]', 1, 'hard'],
  ['Histoire', 'Quel empire islamique a gouverné une grande partie du Moyen-Orient, de l\'Afrique du Nord et de l\'Europe du Sud-Est pendant six siècles ?', '["Empire moghol", "Empire safavide", "Empire ottoman", "Empire abbasside"]', 2, 'hard'],
  ['Histoire', 'Quel traité de 1713 a mis fin à la Guerre de Succession d\'Espagne ?', '["Traité de Westphalie", "Traité de Paris", "Traité d\'Utrecht", "Traité de Tordesillas"]', 2, 'hard'],
  ['Histoire', 'Quel pharaon a ordonné la construction du temple d\'Abou Simbel en Égypte ?', '["Toutankhamon", "Khéops", "Ramsès II", "Akhenaton"]', 2, 'hard'],
  ['Histoire', 'Quel héros de la résistance guinéenne a fondé l\'empire Wassoulou et s\'est opposé à la colonisation française ?', '["El Hadj Oumar Tall", "Samori Touré", "Lat Dior", "Béhanzin"]', 1, 'hard'],
  ['Histoire', 'Quel mouvement de 1955-1968 aux États-Unis a lutté pour les droits civiques des Afro-Américains ?', '["Mouvement abolitionniste", "Mouvement des droits civiques", "Black Panthers", "Harlem Renaissance"]', 1, 'hard'],
  ['Histoire', 'Quelle civilisation d\'Afrique de l\'Est a construit les ruines de pierre du Grand Zimbabwe entre le XIe et le XVe siècle ?', '["Civilisation Swahili", "Civilisation du Grand Zimbabwe", "Empire Aksoumite", "Royaume du Monomotapa"]', 1, 'hard'],
  ['Histoire', 'Quel accord de 1994 a mis fin au génocide des Tutsis au Rwanda et instauré un cessez-le-feu ?', '["Accords de Lusaka", "Accords d\'Arusha", "Accords de Sun City", "Accords de Pretoria"]', 1, 'hard'],
];

export async function POST(req: Request) {
  const admin = await authenticateAdmin(req);
  if (!admin) return errorResponse('Admin access required', 403);

  try {
    const pool = getPool();
    let added = 0, skipped = 0;

    for (const [catName, question, optionsJson, correctAnswer, difficulty] of QUESTIONS) {
      const catRes = await pool.query(
        `INSERT INTO categories (name) VALUES ($1) ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id`,
        [catName]
      );
      const categoryId = catRes.rows[0].id;

      const exists = await pool.query('SELECT id FROM questions WHERE question = $1 AND category_id = $2', [question, categoryId]);
      if (exists.rows.length > 0) { skipped++; continue; }

      await pool.query(
        'INSERT INTO questions (category_id, question, options, correct_answer, difficulty, is_active) VALUES ($1, $2, $3, $4, $5, TRUE)',
        [categoryId, question, optionsJson, correctAnswer, difficulty]
      );
      added++;
    }

    const totalRes = await pool.query('SELECT COUNT(*) as c FROM questions');
    const catCounts = await pool.query('SELECT c.name, COUNT(*) as total FROM questions q JOIN categories c ON q.category_id = c.id GROUP BY c.name ORDER BY c.name');

    return successResponse({
      message: `Batch 2: Added ${added} new questions, skipped ${skipped} duplicates`,
      total_questions: Number(totalRes.rows[0].c),
      categories: catCounts.rows,
    });
  } catch (err: any) {
    return errorResponse('Seed failed: ' + err.message, 500);
  }
}
