import { successResponse, errorResponse, authenticateAdmin } from '../../../_lib/helpers';
import { getPool } from '../../../_lib/db';

type Q = [string, string, string, number, string];

const QUESTIONS: Q[] = [
  // ===================== NATURE (43 questions) =====================
  ['Nature', 'Quel est le biome terrestre qui couvre la plus grande superficie sur Terre ?', '["Forêt tropicale", "Toundra", "Taïga", "Désert"]', 2, 'hard'],
  ['Nature', 'Quel phénomène océanique périodique réchauffe les eaux du Pacifique équatorial et perturbe le climat mondial ?', '["La Niña", "El Niño", "Le Gulf Stream", "L\'upwelling"]', 1, 'medium'],
  ['Nature', 'Quelle espèce de grand singe est endémique de la République Démocratique du Congo ?', '["Gorille de montagne", "Chimpanzé commun", "Bonobo", "Orang-outan"]', 2, 'medium'],
  ['Nature', 'Quel pourcentage de la biodiversité mondiale est estimé vivre dans les forêts tropicales humides ?', '["25%", "50%", "75%", "90%"]', 1, 'hard'],
  ['Nature', 'Comment appelle-t-on la relation symbiotique où les deux organismes bénéficient mutuellement ?', '["Parasitisme", "Commensalisme", "Mutualisme", "Amensalisme"]', 2, 'medium'],
  ['Nature', 'Quel est le nom du courant marin chaud qui traverse l\'Atlantique Nord et adoucit le climat de l\'Europe occidentale ?', '["Courant de Humboldt", "Gulf Stream", "Courant de Benguela", "Courant du Labrador"]', 1, 'hard'],
  ['Nature', 'Quelle est la profondeur approximative de la fosse des Mariannes, le point le plus profond des océans ?', '["7 000 mètres", "9 000 mètres", "11 000 mètres", "13 000 mètres"]', 2, 'hard'],
  ['Nature', 'Quel type de forêt domine le bassin du Congo, deuxième plus grand massif forestier tropical au monde ?', '["Forêt de mangrove", "Forêt équatoriale dense humide", "Forêt de conifères", "Forêt de feuillus tempérée"]', 1, 'medium'],
  ['Nature', 'Quel est le processus par lequel l\'azote atmosphérique est converti en formes utilisables par les plantes ?', '["Nitrification", "Fixation de l\'azote", "Dénitrification", "Ammonification"]', 1, 'hard'],
  ['Nature', 'Quel oiseau africain est connu pour guider les humains vers les ruches d\'abeilles sauvages ?', '["Le calao", "L\'indicateur", "Le tisserin", "Le martin-pêcheur"]', 1, 'hard'],
  ['Nature', 'Combien d\'espèces connues de fourmis existe-t-il approximativement dans le monde ?', '["2 000", "5 000", "12 000", "22 000"]', 3, 'hard'],
  ['Nature', 'Quel est le nom du phénomène de blanchissement des coraux causé par le stress thermique ?', '["Eutrophisation", "Blanchissement corallien", "Acidification", "Sédimentation"]', 1, 'medium'],
  ['Nature', 'Quelle plante carnivore utilise un piège à mâchoires qui se referme en moins d\'une seconde ?', '["Sarracenia", "Drosera", "Dionaea muscipula", "Nepenthes"]', 2, 'hard'],
  ['Nature', 'Quel est le plus grand écosystème d\'eau douce d\'Afrique ?', '["Lac Victoria", "Lac Tanganyika", "Bassin du Congo", "Lac Malawi"]', 2, 'hard'],
  ['Nature', 'Comment s\'appelle la couche de sol gelée en permanence dans les régions polaires ?', '["Pergélisol (permafrost)", "Toundra", "Moraine", "Humus"]', 0, 'hard'],
  ['Nature', 'Quel animal marin possède trois coeurs et du sang bleu ?', '["Méduse", "Pieuvre", "Étoile de mer", "Requin"]', 1, 'hard'],
  ['Nature', 'Quel est le rôle principal des mycorhizes dans l\'écosystème forestier ?', '["Décomposition des feuilles", "Symbiose avec les racines pour l\'absorption des nutriments", "Pollinisation des arbres", "Protection contre les herbivores"]', 1, 'hard'],
  ['Nature', 'Quelle est la vitesse maximale approximative du guépard, l\'animal terrestre le plus rapide ?', '["80 km/h", "100 km/h", "112 km/h", "130 km/h"]', 2, 'medium'],
  ['Nature', 'Quel gaz à effet de serre a un potentiel de réchauffement environ 25 fois supérieur à celui du CO2 sur 100 ans ?', '["Protoxyde d\'azote", "Méthane", "Ozone troposphérique", "CFC-12"]', 1, 'hard'],
  ['Nature', 'Quel est le nom du phénomène par lequel certains organismes produisent de la lumière ?', '["Phosphorescence", "Fluorescence", "Bioluminescence", "Chemiluminescence"]', 2, 'medium'],
  ['Nature', 'Quelle espèce de rhinocéros ne compte plus que deux individus vivants en 2024 ?', '["Rhinocéros de Sumatra", "Rhinocéros de Java", "Rhinocéros blanc du Nord", "Rhinocéros noir"]', 2, 'hard'],
  ['Nature', 'Comment appelle-t-on l\'étude des interactions entre les organismes et leur environnement ?', '["Taxonomie", "Éthologie", "Écologie", "Biogéographie"]', 2, 'easy'],
  ['Nature', 'Quel est le plus grand désert chaud du monde ?', '["Désert du Kalahari", "Désert d\'Arabie", "Désert du Sahara", "Désert du Gobi"]', 2, 'easy'],
  ['Nature', 'Quelle est la durée approximative d\'une migration aller-retour de la sterne arctique ?', '["20 000 km", "40 000 km", "70 000 km", "90 000 km"]', 2, 'hard'],
  ['Nature', 'Quel est le principal pollinisateur des plantes à fleurs dans les écosystèmes tropicaux ?', '["Le vent", "Les abeilles et autres insectes", "Les oiseaux", "Les chauves-souris"]', 1, 'medium'],
  ['Nature', 'Quel type de succession écologique se produit après une perturbation complète du sol, comme une éruption volcanique ?', '["Succession secondaire", "Succession primaire", "Succession cyclique", "Succession régressive"]', 1, 'hard'],
  ['Nature', 'Quel est le fleuve le plus profond du monde ?', '["Amazone", "Nil", "Congo", "Yangtsé"]', 2, 'hard'],
  ['Nature', 'Quel terme désigne la capacité maximale d\'individus qu\'un environnement peut supporter ?', '["Densité de population", "Capacité de charge (K)", "Taux de natalité", "Potentiel biotique"]', 1, 'hard'],
  ['Nature', 'Quel parc national de la RDC est classé au patrimoine mondial et abrite les gorilles de montagne ?', '["Parc national de la Salonga", "Parc national de Kahuzi-Biega", "Parc national des Virunga", "Parc national de la Garamba"]', 2, 'medium'],
  ['Nature', 'Quel phénomène météorologique est caractérisé par un tourbillon de vent violent en forme d\'entonnoir ?', '["Ouragan", "Tornade", "Typhon", "Cyclone"]', 1, 'easy'],
  ['Nature', 'Quelle est la principale différence entre un écosystème lentique et un écosystème lotique ?', '["La température de l\'eau", "L\'eau stagnante vs l\'eau courante", "La salinité", "La profondeur"]', 1, 'hard'],
  ['Nature', 'Quel est l\'arbre le plus ancien connu au monde, un pin Bristlecone, âgé d\'environ combien d\'années ?', '["2 000 ans", "3 000 ans", "5 000 ans", "8 000 ans"]', 2, 'hard'],
  ['Nature', 'Comment appelle-t-on la zone de transition entre deux biomes différents ?', '["Habitat", "Niche écologique", "Écotone", "Biotope"]', 2, 'hard'],
  ['Nature', 'Quel est le mammifère le plus menacé d\'Afrique centrale, victime du braconnage pour son écaille ?', '["Éléphant de forêt", "Pangolin géant", "Okapi", "Hippopotame nain"]', 1, 'hard'],
  ['Nature', 'Quelle couche de l\'atmosphère terrestre est la plus proche de la surface et contient la majeure partie de la météo ?', '["Stratosphère", "Mésosphère", "Troposphère", "Thermosphère"]', 2, 'medium'],
  ['Nature', 'Quel est le phénomène par lequel les plantes perdent de l\'eau par leurs feuilles sous forme de vapeur ?', '["Transpiration", "Évaporation", "Guttation", "Sublimation"]', 0, 'medium'],
  ['Nature', 'Quelle espèce animale endémique de la RDC ressemble à un croisement entre une girafe et un zèbre ?', '["Bongo", "Okapi", "Koudou", "Nyala"]', 1, 'medium'],
  ['Nature', 'Quel est le pourcentage approximatif d\'oxygène dans l\'atmosphère terrestre ?', '["15%", "21%", "30%", "40%"]', 1, 'easy'],
  ['Nature', 'Quel terme désigne un organisme qui se nourrit de matière organique morte et la décompose ?', '["Producteur", "Consommateur primaire", "Détritivore/Décomposeur", "Prédateur apex"]', 2, 'medium'],
  ['Nature', 'Quelle est la cause principale de la sixième extinction de masse actuellement en cours ?', '["Astéroïdes", "Éruptions volcaniques", "Activités humaines", "Changements climatiques naturels"]', 2, 'medium'],
  ['Nature', 'Quel est le plus grand lac d\'Afrique par sa superficie ?', '["Lac Tanganyika", "Lac Malawi", "Lac Tchad", "Lac Victoria"]', 3, 'medium'],
  ['Nature', 'Comment appelle-t-on les organismes capables de vivre dans des conditions extrêmes comme les sources hydrothermales ?', '["Mésophiles", "Thermophiles", "Extrêmophiles", "Psychrophiles"]', 2, 'hard'],
  ['Nature', 'Quel est le nom du cycle biogéochimique qui inclut l\'altération des roches et la sédimentation comme sources de phosphore ?', '["Cycle du carbone", "Cycle de l\'azote", "Cycle du phosphore", "Cycle du soufre"]', 2, 'hard'],

  // ===================== POLITIQUE (43 questions) =====================
  ['Politique', 'En quelle année la République Démocratique du Congo a-t-elle obtenu son indépendance de la Belgique ?', '["1958", "1960", "1962", "1965"]', 1, 'easy'],
  ['Politique', 'Qui fut le premier Premier ministre de la RDC indépendante ?', '["Joseph Kasa-Vubu", "Patrice Lumumba", "Mobutu Sese Seko", "Moise Tshombe"]', 1, 'medium'],
  ['Politique', 'Quel est le nom de l\'organisation panafricaine fondée en 2002 pour remplacer l\'OUA ?', '["CEDEAO", "Union Africaine", "SADC", "COMESA"]', 1, 'medium'],
  ['Politique', 'Combien de provinces la RDC compte-t-elle depuis la réforme territoriale de 2015 ?', '["11", "16", "21", "26"]', 3, 'hard'],
  ['Politique', 'Quel philosophe est considéré comme le père du concept de \"contrat social\" ?', '["John Locke", "Thomas Hobbes", "Jean-Jacques Rousseau", "Montesquieu"]', 2, 'hard'],
  ['Politique', 'Quel article de la Constitution de la RDC de 2006 interdit la modification de la forme républicaine de l\'État ?', '["Article 1", "Article 64", "Article 217", "Article 220"]', 3, 'hard'],
  ['Politique', 'Quel est le nom du tribunal international qui a jugé des crimes de guerre commis en RDC ?', '["TPIR", "CPI (Cour Pénale Internationale)", "CIJ", "TPIY"]', 1, 'hard'],
  ['Politique', 'Quel système politique est caractérisé par la séparation des pouvoirs en trois branches indépendantes ?', '["Monarchie constitutionnelle", "République démocratique", "État unitaire", "Système présidentiel"]', 1, 'medium'],
  ['Politique', 'Quel ancien chef de guerre congolais a été le premier condamné par la CPI en 2012 ?', '["Jean-Pierre Bemba", "Thomas Lubanga", "Bosco Ntaganda", "Laurent Nkunda"]', 1, 'hard'],
  ['Politique', 'Quel est le principe fondamental du droit international qui interdit l\'ingérence dans les affaires intérieures d\'un État ?', '["Droit d\'ingérence humanitaire", "Souveraineté nationale", "Responsabilité de protéger", "Devoir de non-intervention"]', 1, 'hard'],
  ['Politique', 'Quel pays africain a été le premier à obtenir son indépendance au sud du Sahara en 1957 ?', '["Nigeria", "Ghana", "Sénégal", "Éthiopie"]', 1, 'hard'],
  ['Politique', 'Combien de membres permanents siègent au Conseil de sécurité des Nations Unies ?', '["3", "5", "7", "10"]', 1, 'medium'],
  ['Politique', 'Quel est le nom de la conférence de 1884-1885 qui a partagé l\'Afrique entre les puissances coloniales européennes ?', '["Conférence de Versailles", "Conférence de Yalta", "Conférence de Berlin", "Conférence de Bandung"]', 2, 'medium'],
  ['Politique', 'Quel type de scrutin est utilisé pour les élections présidentielles en RDC ?', '["Scrutin proportionnel", "Scrutin majoritaire à deux tours", "Scrutin majoritaire à un tour", "Scrutin mixte"]', 2, 'hard'],
  ['Politique', 'Quel leader politique congolais a dirigé le pays sous le nom de Zaïre de 1965 à 1997 ?', '["Laurent-Désiré Kabila", "Mobutu Sese Seko", "Joseph Kabila", "Étienne Tshisekedi"]', 1, 'easy'],
  ['Politique', 'Quel traité a établi la Communauté Économique des États de l\'Afrique Centrale (CEEAC) ?', '["Traité de Libreville", "Traité d\'Abuja", "Traité de Kinshasa", "Traité de Lagos"]', 0, 'hard'],
  ['Politique', 'Quel est le concept politique selon lequel le pouvoir émane du peuple et s\'exerce par ses représentants ?', '["Autocratie", "Théocratie", "Démocratie représentative", "Oligarchie"]', 2, 'medium'],
  ['Politique', 'Quel accord de paix de 2002 a mis fin à la deuxième guerre du Congo ?', '["Accord de Lusaka", "Accord de Sun City", "Accord de Pretoria", "Accord d\'Addis-Abeba"]', 1, 'hard'],
  ['Politique', 'Quel organe de l\'Union Africaine est chargé du maintien de la paix et de la sécurité sur le continent ?', '["Commission de l\'UA", "Conseil de Paix et de Sécurité", "Parlement panafricain", "Cour africaine des droits de l\'homme"]', 1, 'hard'],
  ['Politique', 'Quel philosophe politique a théorisé la séparation des pouvoirs législatif, exécutif et judiciaire ?', '["Jean Bodin", "Montesquieu", "Machiavel", "Alexis de Tocqueville"]', 1, 'medium'],
  ['Politique', 'Quel est le nom de l\'institution électorale indépendante chargée d\'organiser les élections en RDC ?', '["CEI", "CENI", "CNE", "INEC"]', 1, 'hard'],
  ['Politique', 'Quel pays africain n\'a jamais été colonisé par une puissance européenne, avec l\'Éthiopie ?', '["Liberia", "Sierra Leone", "Somalie", "Djibouti"]', 0, 'hard'],
  ['Politique', 'Quel est le mécanisme onusien permettant aux grandes puissances de bloquer une résolution au Conseil de sécurité ?', '["Motion de censure", "Droit de veto", "Abstention constructive", "Clause de sauvegarde"]', 1, 'medium'],
  ['Politique', 'En quelle année Félix Tshisekedi est-il devenu président de la RDC pour la première fois ?', '["2017", "2018", "2019", "2020"]', 2, 'medium'],
  ['Politique', 'Quel concept désigne le transfert pacifique du pouvoir d\'un dirigeant à un autre selon les règles constitutionnelles ?', '["Coup d\'État", "Alternance démocratique", "Succession dynastique", "Transition politique"]', 1, 'medium'],
  ['Politique', 'Quelle organisation sous-régionale regroupe les pays d\'Afrique australe, dont la RDC est membre ?', '["CEDEAO", "CEMAC", "SADC", "IGAD"]', 2, 'hard'],
  ['Politique', 'Quel est le nom de la doctrine politique qui prône l\'unité politique des peuples africains ?', '["Négritude", "Panafricanisme", "Afrocentrisme", "Nationalisme africain"]', 1, 'medium'],
  ['Politique', 'Quel ancien secrétaire général des Nations Unies était d\'origine ghanéenne ?', '["Boutros Boutros-Ghali", "Ban Ki-moon", "Kofi Annan", "António Guterres"]', 2, 'medium'],
  ['Politique', 'Quel article de la Déclaration universelle des droits de l\'homme consacre le droit à la vie, à la liberté et à la sûreté ?', '["Article 1", "Article 3", "Article 5", "Article 7"]', 1, 'hard'],
  ['Politique', 'Quel est le nom du mouvement politique qui a mené la lutte pour l\'indépendance du Congo belge sous Lumumba ?', '["ABAKO", "MNC (Mouvement National Congolais)", "CONAKAT", "PSA"]', 1, 'hard'],
  ['Politique', 'Quel type de gouvernement est caractérisé par le pouvoir concentré entre les mains d\'un petit groupe d\'élites ?', '["Démocratie", "Oligarchie", "Anarchie", "Théocratie"]', 1, 'hard'],
  ['Politique', 'Quelle institution internationale a son siège à La Haye et règle les différends entre États ?', '["CPI", "CIJ (Cour Internationale de Justice)", "CEDH", "Tribunal de la mer"]', 1, 'hard'],
  ['Politique', 'Quel est le nombre total de sièges à l\'Assemblée nationale de la RDC ?', '["300", "400", "500", "600"]', 2, 'hard'],
  ['Politique', 'Quel est le nom de la mission de maintien de la paix de l\'ONU en RDC, la plus grande au monde à sa création ?', '["MINUSMA", "MONUSCO", "MINUAD", "ONUCI"]', 1, 'hard'],
  ['Politique', 'Quel concept du droit constitutionnel désigne la loi fondamentale suprême d\'un État ?', '["Code civil", "Constitution", "Ordonnance", "Décret-loi"]', 1, 'easy'],
  ['Politique', 'Quel roi belge a possédé le Congo comme propriété personnelle avant qu\'il ne devienne colonie belge ?', '["Léopold Ier", "Léopold II", "Albert Ier", "Baudouin"]', 1, 'medium'],
  ['Politique', 'Quelle est la plus haute juridiction de la RDC selon la Constitution de 2006 ?', '["Cour suprême", "Cour constitutionnelle", "Conseil d\'État", "Cour de cassation"]', 1, 'hard'],
  ['Politique', 'Quel accord international de 2015 sur le climat a été signé par 196 pays ?', '["Protocole de Kyoto", "Accord de Paris", "Accord de Copenhague", "Protocole de Montréal"]', 1, 'medium'],
  ['Politique', 'Quel est le système électoral qui attribue les sièges proportionnellement aux voix obtenues par chaque parti ?', '["Scrutin majoritaire", "Scrutin proportionnel", "Scrutin uninominal", "Scrutin de liste bloquée"]', 1, 'hard'],
  ['Politique', 'Quel conflit armé en RDC (1998-2003) est souvent qualifié de \"guerre mondiale africaine\" ?', '["Première guerre du Congo", "Deuxième guerre du Congo", "Guerre du M23", "Guerre du Katanga"]', 1, 'hard'],
  ['Politique', 'Quelle charte africaine adoptée en 1981 protège les droits de l\'homme et des peuples sur le continent ?', '["Charte de l\'OUA", "Charte africaine des droits de l\'homme et des peuples (Charte de Banjul)", "Déclaration de Kampala", "Protocole de Maputo"]', 1, 'hard'],
  ['Politique', 'Quel est le mandat présidentiel en RDC selon la Constitution et combien de fois est-il renouvelable ?', '["5 ans, renouvelable deux fois", "5 ans, renouvelable une fois", "7 ans, non renouvelable", "4 ans, renouvelable une fois"]', 1, 'hard'],
  ['Politique', 'Quel organe législatif bicaméral de la RDC comprend l\'Assemblée nationale et le Sénat ?', '["Conseil national", "Parlement", "Congrès", "Diète"]', 1, 'medium'],

  // ===================== SPORT (43 questions) =====================
  ['Sport', 'Quel pays africain a remporté la première Coupe du Monde de football organisée sur le continent africain en 2010 ?', '["Afrique du Sud", "Ghana", "Espagne", "Pays-Bas"]', 2, 'medium'],
  ['Sport', 'Quel athlète jamaïcain détient le record du monde du 100 mètres avec 9,58 secondes ?', '["Tyson Gay", "Usain Bolt", "Yohan Blake", "Asafa Powell"]', 1, 'easy'],
  ['Sport', 'Quel pays a remporté le plus de Coupes d\'Afrique des Nations de football (CAN) ?', '["Nigeria", "Ghana", "Cameroun", "Égypte"]', 3, 'medium'],
  ['Sport', 'Quel boxeur a réalisé le célèbre combat \"Rumble in the Jungle\" à Kinshasa en 1974 contre George Foreman ?', '["Joe Frazier", "Muhammad Ali", "Mike Tyson", "Sugar Ray Leonard"]', 1, 'medium'],
  ['Sport', 'En quelle année les Jeux Olympiques modernes ont-ils été rétablis à Athènes ?', '["1888", "1892", "1896", "1900"]', 2, 'medium'],
  ['Sport', 'Quel footballeur congolais a été élu meilleur joueur africain de l\'année par la CAF en 2024 ?', '["Cédric Bakambu", "Yannick Bolasie", "Chancel Mbemba", "Simon Banza"]', 0, 'hard'],
  ['Sport', 'Quel sport d\'origine japonaise est devenu discipline olympique pour la première fois aux JO de Tokyo 2020 ?', '["Karaté", "Judo", "Taekwondo", "Sumo"]', 0, 'hard'],
  ['Sport', 'Quel athlète éthiopien a remporté le marathon olympique pieds nus à Rome en 1960 ?', '["Haile Gebrselassie", "Kenenisa Bekele", "Abebe Bikila", "Miruts Yifter"]', 2, 'hard'],
  ['Sport', 'Combien de joueurs composent une équipe de rugby à XV sur le terrain ?', '["11", "13", "15", "18"]', 2, 'medium'],
  ['Sport', 'Quel pays détient le record de victoires en Coupe du Monde de football masculin avec 5 titres ?', '["Allemagne", "Italie", "Argentine", "Brésil"]', 3, 'medium'],
  ['Sport', 'Quelle nageuse américaine est la femme la plus décorée de l\'histoire des JO en natation ?', '["Katie Ledecky", "Jenny Thompson", "Missy Franklin", "Natalie Coughlin"]', 0, 'hard'],
  ['Sport', 'Quel est le nom du tournoi de tennis joué sur terre battue à Paris chaque année ?', '["Open d\'Australie", "Wimbledon", "Roland-Garros", "US Open"]', 2, 'easy'],
  ['Sport', 'Quel sprinter américain a été déchu de ses médailles olympiques pour dopage après les JO de Séoul 1988 ?', '["Carl Lewis", "Ben Johnson", "Maurice Greene", "Linford Christie"]', 1, 'hard'],
  ['Sport', 'Quel pays africain a atteint les quarts de finale de la Coupe du Monde 2010, une première pour le continent ?', '["Cameroun", "Nigeria", "Ghana", "Côte d\'Ivoire"]', 2, 'hard'],
  ['Sport', 'Quel est le record du monde du saut en hauteur masculin détenu par Javier Sotomayor ?', '["2,35 m", "2,40 m", "2,45 m", "2,50 m"]', 2, 'hard'],
  ['Sport', 'Quel club de football congolais a remporté la Ligue des champions de la CAF en 2009 ?', '["AS Vita Club", "TP Mazembe", "DC Motema Pembe", "AS V.Club"]', 1, 'hard'],
  ['Sport', 'Combien de sets faut-il gagner pour remporter un match de tennis masculin en Grand Chelem ?', '["2", "3", "4", "5"]', 1, 'medium'],
  ['Sport', 'Quel athlète kényan est considéré comme le plus grand marathonien de l\'histoire avec un record de 2h00:35 ?', '["Eliud Kipchoge", "Wilson Kipsang", "Dennis Kimetto", "Geoffrey Mutai"]', 0, 'hard'],
  ['Sport', 'Quel sport collectif se joue avec un ballon ovale et oppose deux équipes de 7 joueurs dans sa variante olympique ?', '["Football américain", "Rugby à sept", "Football australien", "Handball"]', 1, 'medium'],
  ['Sport', 'En quelle année la Coupe du Monde de football féminin a-t-elle été organisée pour la première fois ?', '["1987", "1991", "1995", "1999"]', 1, 'hard'],
  ['Sport', 'Quel gymnaste roumaine a obtenu la première note parfaite de 10 aux JO de Montréal en 1976 ?', '["Larisa Latynina", "Nadia Comaneci", "Simone Biles", "Svetlana Khorkina"]', 1, 'medium'],
  ['Sport', 'Quel pays a accueilli les premiers Jeux Olympiques d\'hiver en 1924 ?', '["Suisse", "Norvège", "France", "Autriche"]', 2, 'hard'],
  ['Sport', 'Quel footballeur camerounais est devenu le plus vieux buteur de l\'histoire de la Coupe du Monde en 1994 ?', '["Samuel Eto\'o", "Roger Milla", "Patrick Mboma", "Rigobert Song"]', 1, 'hard'],
  ['Sport', 'Quel est le nom de la course cycliste la plus prestigieuse au monde, disputée chaque année en juillet en France ?', '["Giro d\'Italia", "Vuelta a España", "Tour de France", "Paris-Roubaix"]', 2, 'easy'],
  ['Sport', 'Quel pays a remporté la Coupe du Monde de football 2022 au Qatar ?', '["France", "Brésil", "Argentine", "Croatie"]', 2, 'easy'],
  ['Sport', 'Quel athlète a remporté 8 médailles d\'or en natation aux seuls JO de Pékin 2008 ?', '["Ian Thorpe", "Michael Phelps", "Ryan Lochte", "Mark Spitz"]', 1, 'medium'],
  ['Sport', 'Quel sport d\'origine indienne se joue avec un volant (shuttlecock) et une raquette ?', '["Tennis de table", "Squash", "Badminton", "Pelote basque"]', 2, 'easy'],
  ['Sport', 'Quelle équipe nationale africaine est surnommée les \"Léopards\" ?', '["Cameroun", "Nigeria", "RD Congo", "Côte d\'Ivoire"]', 2, 'medium'],
  ['Sport', 'Quel record du monde d\'athlétisme féminin est resté inégalé depuis 1988, détenu par Florence Griffith-Joyner au 100m ?', '["10,49 s", "10,62 s", "10,76 s", "10,81 s"]', 0, 'hard'],
  ['Sport', 'Quel pays a boycotté les JO de Moscou 1980 pour protester contre l\'invasion soviétique de l\'Afghanistan ?', '["France", "Royaume-Uni", "États-Unis", "Allemagne de l\'Ouest"]', 2, 'hard'],
  ['Sport', 'Quel est le nombre maximum de remplacements autorisés dans un match de football officiel selon les règles standard ?', '["3", "4", "5", "6"]', 2, 'hard'],
  ['Sport', 'Quel sportif sud-africain a été le premier rugbyman noir à marquer un essai en finale de Coupe du Monde en 2019 ?', '["Siya Kolisi", "Makazole Mapimpi", "Cheslin Kolbe", "Bryan Habana"]', 1, 'hard'],
  ['Sport', 'Quel art martial coréen est devenu sport olympique à partir des JO de Sydney 2000 ?', '["Judo", "Karaté", "Taekwondo", "Kung-fu"]', 2, 'medium'],
  ['Sport', 'Quel est le nom du stade de Kinshasa, le plus grand de la RDC ?', '["Stade Tata Raphaël", "Stade des Martyrs", "Stade TP Mazembe", "Stade du 30 Juin"]', 1, 'medium'],
  ['Sport', 'Quelle épreuve olympique d\'athlétisme combine dix disciplines différentes sur deux jours ?', '["Heptathlon", "Pentathlon", "Décathlon", "Triathlon"]', 2, 'medium'],
  ['Sport', 'Quel joueur de basketball américain est considéré comme le plus grand de tous les temps avec 6 titres NBA aux Chicago Bulls ?', '["Kobe Bryant", "LeBron James", "Michael Jordan", "Kareem Abdul-Jabbar"]', 2, 'medium'],
  ['Sport', 'Quel pays africain a créé la surprise en atteignant la finale de la CAN 2023 pour la première fois ?', '["Cap-Vert", "Gambie", "Guinée équatoriale", "Nigeria"]', 3, 'hard'],
  ['Sport', 'Quelle discipline des JO d\'été consiste en une combinaison de natation, cyclisme et course à pied ?', '["Pentathlon moderne", "Triathlon", "Biathlon", "Décathlon"]', 1, 'medium'],
  ['Sport', 'Quel golfeur sud-africain a remporté trois fois le British Open et est une légende du sport mondial ?', '["Ernie Els", "Retief Goosen", "Gary Player", "Louis Oosthuizen"]', 2, 'hard'],
  ['Sport', 'En quelle année les femmes ont-elles été autorisées à participer au marathon olympique pour la première fois ?', '["1972", "1976", "1980", "1984"]', 3, 'hard'],
  ['Sport', 'Quel club congolais est le seul club africain non nord-africain à avoir atteint la finale de la Coupe du monde des clubs FIFA ?', '["AS Vita Club", "TP Mazembe", "DC Motema Pembe", "CS Don Bosco"]', 1, 'hard'],
  ['Sport', 'Quel athlète américain a remporté 4 médailles d\'or aux JO de Berlin 1936, humiliant l\'idéologie nazie ?', '["Joe Louis", "Jesse Owens", "Ralph Metcalfe", "Mack Robinson"]', 1, 'hard'],
  ['Sport', 'Quel est le nom de la compétition internationale de football qui se déroule tous les deux ans entre nations africaines ?', '["Ligue des Champions CAF", "CHAN", "Coupe d\'Afrique des Nations (CAN)", "Super Coupe d\'Afrique"]', 2, 'easy'],

  // ===================== SCIENCES (43 questions) =====================
  ['Sciences', 'Quel est le nom de la particule hypothétique responsable de la masse des autres particules, découverte en 2012 au CERN ?', '["Graviton", "Boson de Higgs", "Tachyon", "Gluon"]', 1, 'hard'],
  ['Sciences', 'Quelle est la constante de Planck utilisée en mécanique quantique, exprimée en joules-secondes ?', '["6,626 x 10⁻³⁴ J.s", "3,14 x 10⁻¹⁵ J.s", "1,602 x 10⁻¹⁹ J.s", "9,109 x 10⁻³¹ J.s"]', 0, 'hard'],
  ['Sciences', 'Quel physicien a formulé le principe d\'incertitude selon lequel on ne peut pas connaître simultanément la position et la vitesse exactes d\'une particule ?', '["Niels Bohr", "Werner Heisenberg", "Max Planck", "Erwin Schrödinger"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom de la théorie qui unifie l\'électromagnétisme et la force nucléaire faible ?', '["Théorie des cordes", "Théorie électrofaible", "Théorie du tout", "Chromodynamique quantique"]', 1, 'hard'],
  ['Sciences', 'Quelle est la durée de demi-vie du carbone 14, utilisé pour la datation archéologique ?', '["1 730 ans", "3 200 ans", "5 730 ans", "11 460 ans"]', 2, 'hard'],
  ['Sciences', 'Quel scientifique a proposé le modèle planétaire de l\'atome avec un noyau central entouré d\'électrons ?', '["J.J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"]', 1, 'hard'],
  ['Sciences', 'Quelle est la troisième loi de la thermodynamique ?', '["L\'énergie se conserve", "L\'entropie d\'un système isolé augmente", "L\'entropie d\'un cristal parfait au zéro absolu est nulle", "La chaleur ne peut pas passer du froid au chaud spontanément"]', 2, 'hard'],
  ['Sciences', 'Quel est le nom de l\'effet par lequel la lumière change de fréquence lorsqu\'elle est réfléchie par un objet en mouvement ?', '["Effet Compton", "Effet Doppler", "Effet photoélectrique", "Effet Zeeman"]', 1, 'hard'],
  ['Sciences', 'Quelle structure de l\'ADN a été décrite par Watson et Crick en 1953 ?', '["Simple hélice", "Double hélice", "Triple hélice", "Structure en feuillet"]', 1, 'medium'],
  ['Sciences', 'Quel est le nom de la force fondamentale qui maintient les quarks ensemble à l\'intérieur des protons et neutrons ?', '["Force électromagnétique", "Force gravitationnelle", "Force nucléaire forte", "Force nucléaire faible"]', 2, 'hard'],
  ['Sciences', 'Quelle est la distance approximative de la Terre à la galaxie d\'Andromède ?', '["500 000 années-lumière", "2,5 millions d\'années-lumière", "10 millions d\'années-lumière", "50 millions d\'années-lumière"]', 1, 'hard'],
  ['Sciences', 'Quel organe du corps humain possède environ 86 milliards de neurones ?', '["Moelle épinière", "Cerveau", "Intestin", "Rétine"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom du processus cellulaire par lequel les cellules programment leur propre mort ?', '["Nécrose", "Apoptose", "Lyse", "Autophagie"]', 1, 'hard'],
  ['Sciences', 'Quelle est la vitesse de libération nécessaire pour quitter le champ gravitationnel terrestre ?', '["7,9 km/s", "11,2 km/s", "15,5 km/s", "25 km/s"]', 1, 'hard'],
  ['Sciences', 'Quel scientifique a reçu le prix Nobel de physique en 1921 pour son explication de l\'effet photoélectrique ?', '["Max Planck", "Albert Einstein", "Niels Bohr", "Werner Heisenberg"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom de la barrière théorique qui empêche un objet massif de dépasser la vitesse de la lumière ?', '["Mur de Planck", "Barrière de Lorentz", "Limite relativiste", "Mur du son lumineux"]', 2, 'hard'],
  ['Sciences', 'Quelle est la plus petite unité fonctionnelle du rein humain ?', '["Alvéole", "Néphron", "Neurone", "Hépatocyte"]', 1, 'hard'],
  ['Sciences', 'Quel phénomène quantique permet à une particule de traverser une barrière d\'énergie qu\'elle ne devrait pas pouvoir franchir classiquement ?', '["Superposition quantique", "Effet tunnel", "Intrication quantique", "Décohérence"]', 1, 'hard'],
  ['Sciences', 'Quelle planète naine, découverte en 2005, est plus massive que Pluton ?', '["Hauméa", "Makémaké", "Éris", "Cérès"]', 2, 'hard'],
  ['Sciences', 'Quel est le nom du cycle de réactions biochimiques qui produit de l\'ATP dans les mitochondries ?', '["Glycolyse", "Cycle de Krebs", "Chaîne de transport d\'électrons", "Cycle de Calvin"]', 1, 'hard'],
  ['Sciences', 'Quelle est la température approximative à la surface du Soleil ?', '["2 500°C", "5 500°C", "10 000°C", "15 000°C"]', 1, 'medium'],
  ['Sciences', 'Quel type de rayonnement électromagnétique a la plus grande longueur d\'onde ?', '["Rayons gamma", "Rayons X", "Lumière visible", "Ondes radio"]', 3, 'medium'],
  ['Sciences', 'Quel scientifique a découvert la radioactivité naturelle en 1896 ?', '["Pierre Curie", "Henri Becquerel", "Marie Curie", "Ernest Rutherford"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom du phénomène où la lumière se comporte à la fois comme une onde et comme une particule ?', '["Dualité onde-particule", "Principe de superposition", "Diffraction", "Interférence"]', 0, 'hard'],
  ['Sciences', 'Combien de paires de bases contient approximativement le génome humain ?', '["300 millions", "1 milliard", "3 milliards", "6 milliards"]', 2, 'hard'],
  ['Sciences', 'Quel est le nom de l\'enzyme qui copie l\'ADN lors de la réplication ?', '["ARN polymérase", "ADN polymérase", "Hélicase", "Ligase"]', 1, 'hard'],
  ['Sciences', 'Quelle est la loi physique qui stipule que la pression d\'un gaz est inversement proportionnelle à son volume à température constante ?', '["Loi de Charles", "Loi de Boyle-Mariotte", "Loi d\'Avogadro", "Loi de Gay-Lussac"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom du télescope spatial lancé en 2021 pour succéder à Hubble ?', '["Spitzer", "Kepler", "James Webb", "Chandra"]', 2, 'medium'],
  ['Sciences', 'Quelle protéine fibreuse est le principal composant structurel de la peau, des os et des tendons ?', '["Kératine", "Collagène", "Élastine", "Actine"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom de la réaction nucléaire qui alimente les étoiles, fusionnant l\'hydrogène en hélium ?', '["Fission nucléaire", "Fusion nucléaire", "Désintégration bêta", "Capture neutronique"]', 1, 'medium'],
  ['Sciences', 'Quel mathématicien et physicien a inventé le calcul infinitésimal indépendamment de Newton ?', '["Leonhard Euler", "Gottfried Wilhelm Leibniz", "Carl Friedrich Gauss", "Blaise Pascal"]', 1, 'hard'],
  ['Sciences', 'Quelle est la constante gravitationnelle universelle G exprimée en unités SI ?', '["6,674 x 10⁻¹¹ N.m²/kg²", "9,81 m/s²", "3 x 10⁸ m/s", "1,602 x 10⁻¹⁹ C"]', 0, 'hard'],
  ['Sciences', 'Quel est le nom de la couche de cellules nerveuses à l\'arrière de l\'oeil qui détecte la lumière ?', '["Cornée", "Iris", "Rétine", "Cristallin"]', 2, 'medium'],
  ['Sciences', 'Quelle est la loi de Hubble en cosmologie ?', '["Les galaxies attirent la matière noire", "Les galaxies s\'éloignent à une vitesse proportionnelle à leur distance", "L\'univers est statique", "La lumière se courbe autour des masses"]', 1, 'hard'],
  ['Sciences', 'Quel est le nombre quantique qui détermine la forme de l\'orbitale atomique ?', '["Nombre quantique principal (n)", "Nombre quantique azimutal (l)", "Nombre quantique magnétique (ml)", "Nombre quantique de spin (ms)"]', 1, 'hard'],
  ['Sciences', 'Quel est le plus grand os du corps humain ?', '["Humérus", "Tibia", "Fémur", "Péroné"]', 2, 'medium'],
  ['Sciences', 'Quel physicien a proposé l\'expérience de pensée du chat à la fois mort et vivant pour illustrer les paradoxes de la mécanique quantique ?', '["Heisenberg", "Bohr", "Schrödinger", "Dirac"]', 2, 'medium'],
  ['Sciences', 'Quelle est la principale source d\'énergie des cellules vivantes ?', '["Glucose", "ATP (adénosine triphosphate)", "ADN", "Lipides"]', 1, 'hard'],
  ['Sciences', 'Quel est le nom de l\'horizon des événements, la limite au-delà de laquelle rien ne peut s\'échapper d\'un trou noir ?', '["Singularité", "Rayon de Schwarzschild", "Horizon de Cauchy", "Ergosphère"]', 1, 'hard'],
  ['Sciences', 'Quelle est la molécule porteuse de l\'information génétique transmise lors de la transcription ?', '["ADN", "ARN messager", "ARN de transfert", "ARN ribosomal"]', 1, 'hard'],
  ['Sciences', 'Quel est le principe de la relativité restreinte qui affirme que les lois de la physique sont les mêmes dans tous les référentiels inertiels ?', '["Principe d\'équivalence", "Principe de relativité", "Principe de correspondance", "Principe de moindre action"]', 1, 'hard'],
  ['Sciences', 'Quelle est la masse approximative du proton en kilogrammes ?', '["1,673 x 10⁻²⁷ kg", "9,109 x 10⁻³¹ kg", "6,626 x 10⁻³⁴ kg", "1,602 x 10⁻¹⁹ kg"]', 0, 'hard'],
  ['Sciences', 'Quel neurotransmetteur est principalement associé au plaisir et à la récompense dans le cerveau ?', '["Sérotonine", "Dopamine", "Acétylcholine", "GABA"]', 1, 'medium'],

  // ===================== CHIMIE (43 questions) =====================
  ['Chimie', 'Quel chimiste russe a créé le premier tableau périodique des éléments en 1869 ?', '["Antoine Lavoisier", "Dmitri Mendeleïev", "John Dalton", "Linus Pauling"]', 1, 'medium'],
  ['Chimie', 'Quel est le nombre atomique du carbone ?', '["4", "6", "8", "12"]', 1, 'medium'],
  ['Chimie', 'Quel type de liaison chimique implique le partage d\'électrons entre deux atomes ?', '["Liaison ionique", "Liaison covalente", "Liaison métallique", "Liaison hydrogène"]', 1, 'medium'],
  ['Chimie', 'Quel est le nom de la réaction chimique entre un acide et une base qui produit de l\'eau et un sel ?', '["Oxydoréduction", "Neutralisation", "Combustion", "Polymérisation"]', 1, 'medium'],
  ['Chimie', 'Quel élément chimique a le symbole W et le numéro atomique 74 ?', '["Wolfram (Tungstène)", "Vanadium", "Zinc", "Xénon"]', 0, 'hard'],
  ['Chimie', 'Quelle est la géométrie moléculaire de la molécule de méthane (CH4) selon la théorie VSEPR ?', '["Linéaire", "Trigonale plane", "Tétraédrique", "Octaédrique"]', 2, 'hard'],
  ['Chimie', 'Quel est le nom du processus industriel de synthèse de l\'ammoniac à partir d\'azote et d\'hydrogène ?', '["Procédé Solvay", "Procédé Haber-Bosch", "Procédé Contact", "Procédé Ostwald"]', 1, 'hard'],
  ['Chimie', 'Quelle est la configuration électronique de l\'atome de fer (Fe, Z=26) dans son état fondamental ?', '["[Ar] 3d⁶ 4s²", "[Ar] 3d⁸", "[Ar] 3d⁵ 4s²", "[Ar] 4s² 3d⁶ 4p²"]', 0, 'hard'],
  ['Chimie', 'Quel acide aminé est le seul à ne pas posséder de carbone asymétrique ?', '["Alanine", "Glycine", "Valine", "Leucine"]', 1, 'hard'],
  ['Chimie', 'Quel est le nom de la loi qui stipule que dans une réaction à l\'équilibre, le rapport des concentrations des produits sur les réactifs est constant ?', '["Loi de Dalton", "Loi d\'action de masse", "Loi de Hess", "Loi de Raoult"]', 1, 'hard'],
  ['Chimie', 'Quel est le pH d\'une solution d\'acide chlorhydrique (HCl) à 0,01 mol/L ?', '["1", "2", "3", "4"]', 1, 'hard'],
  ['Chimie', 'Quel type d\'isomérie est présent lorsque deux molécules ont la même formule mais une disposition spatiale différente autour d\'une double liaison ?', '["Isomérie de chaîne", "Isomérie de fonction", "Isomérie Z/E (cis-trans)", "Isomérie de position"]', 2, 'hard'],
  ['Chimie', 'Quel chimiste français est considéré comme le père de la chimie moderne et a démontré la loi de conservation de la masse ?', '["Joseph Priestley", "Antoine Lavoisier", "Louis Pasteur", "Henri Moissan"]', 1, 'hard'],
  ['Chimie', 'Quel est le nombre d\'oxydation du manganèse dans l\'ion permanganate (MnO4⁻) ?', '["+3", "+5", "+7", "+4"]', 2, 'hard'],
  ['Chimie', 'Quelle est la formule chimique du glucose ?', '["C5H10O5", "C6H12O6", "C6H10O5", "C12H22O11"]', 1, 'medium'],
  ['Chimie', 'Quel est le principe de Le Chatelier en chimie ?', '["Un système à l\'équilibre réagit pour s\'opposer à toute perturbation", "La vitesse de réaction double tous les 10°C", "Les gaz parfaits obéissent à PV=nRT", "L\'énergie se conserve dans une réaction chimique"]', 0, 'hard'],
  ['Chimie', 'Quel est le nom du groupe fonctionnel -COOH présent dans les acides organiques ?', '["Hydroxyle", "Carbonyle", "Carboxyle", "Ester"]', 2, 'medium'],
  ['Chimie', 'Quelle est la masse molaire de l\'eau (H2O) ?', '["16 g/mol", "18 g/mol", "20 g/mol", "22 g/mol"]', 1, 'easy'],
  ['Chimie', 'Quel est le nom de la réaction qui convertit un alcool en aldéhyde par perte d\'hydrogène ?', '["Hydratation", "Déshydrogénation (oxydation ménagée)", "Estérification", "Hydrogénation"]', 1, 'hard'],
  ['Chimie', 'Quel élément chimique est le plus électronégatif selon l\'échelle de Pauling ?', '["Oxygène", "Chlore", "Fluor", "Azote"]', 2, 'hard'],
  ['Chimie', 'Quel est le nom de la couche électronique qui peut contenir un maximum de 18 électrons ?', '["Couche K", "Couche L", "Couche M", "Couche N"]', 2, 'hard'],
  ['Chimie', 'Quelle technique chromatographique sépare les composés en fonction de leur affinité avec une phase stationnaire et une phase mobile ?', '["Distillation", "Cristallisation", "Chromatographie", "Centrifugation"]', 2, 'medium'],
  ['Chimie', 'Quel est le nom de la réaction entre un acide carboxylique et un alcool pour former un ester ?', '["Saponification", "Estérification", "Polymérisation", "Hydrolyse"]', 1, 'hard'],
  ['Chimie', 'Quel élément de transition est essentiel au transport de l\'oxygène dans l\'hémoglobine ?', '["Cuivre", "Zinc", "Fer", "Cobalt"]', 2, 'medium'],
  ['Chimie', 'Quelle est la structure tridimensionnelle de la molécule d\'eau selon la théorie VSEPR ?', '["Linéaire", "Coudée (angulaire)", "Trigonale plane", "Tétraédrique"]', 1, 'hard'],
  ['Chimie', 'Quel est le nom du processus de décomposition d\'une substance par l\'eau ?', '["Électrolyse", "Hydrolyse", "Pyrolyse", "Photolyse"]', 1, 'hard'],
  ['Chimie', 'Quel scientifique a reçu le prix Nobel de chimie deux fois, en 1954 et le prix Nobel de la paix en 1962 ?', '["Marie Curie", "Linus Pauling", "Frederick Sanger", "John Bardeen"]', 1, 'hard'],
  ['Chimie', 'Quel est le nom de l\'allotrope du carbone composé de feuillets hexagonaux empilés ?', '["Diamant", "Graphite", "Fullerène", "Graphène"]', 1, 'hard'],
  ['Chimie', 'Quelle est la valeur de la constante d\'Avogadro ?', '["6,022 x 10²³ mol⁻¹", "3,14 x 10⁸ mol⁻¹", "8,314 J/mol.K", "1,38 x 10⁻²³ J/K"]', 0, 'medium'],
  ['Chimie', 'Quel type de polymère est formé par la réaction de condensation avec élimination d\'eau ?', '["Polymère d\'addition", "Polymère de condensation", "Copolymère", "Élastomère"]', 1, 'hard'],
  ['Chimie', 'Quel est le nom de la loi qui relie l\'absorbance d\'une solution à sa concentration et l\'épaisseur de la cuve ?', '["Loi de Henry", "Loi de Beer-Lambert", "Loi de Raoult", "Loi de Graham"]', 1, 'hard'],
  ['Chimie', 'Quel est le gaz noble qui a le numéro atomique le plus élevé parmi les éléments stables ?', '["Néon", "Argon", "Krypton", "Radon"]', 3, 'hard'],
  ['Chimie', 'Quelle est la différence principale entre une réaction exothermique et une réaction endothermique ?', '["La vitesse de réaction", "La libération ou l\'absorption de chaleur", "Le nombre de produits formés", "La présence d\'un catalyseur"]', 1, 'medium'],
  ['Chimie', 'Quel est le nom de l\'enzyme qui catalyse la décomposition du peroxyde d\'hydrogène en eau et oxygène ?', '["Lipase", "Amylase", "Catalase", "Protéase"]', 2, 'hard'],
  ['Chimie', 'Quel est le nombre quantique principal de la couche de valence du sodium (Na, Z=11) ?', '["1", "2", "3", "4"]', 2, 'hard'],
  ['Chimie', 'Quel composé organique est le constituant principal du vinaigre ?', '["Acide formique", "Acide acétique", "Acide citrique", "Acide lactique"]', 1, 'medium'],
  ['Chimie', 'Quel est le nom de la réaction inverse de l\'estérification ?', '["Polymérisation", "Saponification/Hydrolyse", "Combustion", "Neutralisation"]', 1, 'hard'],
  ['Chimie', 'Quel est le nombre de liaisons covalentes que le carbone peut former en raison de ses 4 électrons de valence ?', '["2", "3", "4", "6"]', 2, 'medium'],
  ['Chimie', 'Quel procédé industriel est utilisé pour la fabrication de l\'acide sulfurique ?', '["Procédé Haber", "Procédé Contact", "Procédé Solvay", "Procédé Hall-Héroult"]', 1, 'hard'],
  ['Chimie', 'Quelle est la molécule organique qui sert de monomère pour la synthèse du polyéthylène ?', '["Propylène", "Éthylène", "Styrène", "Butadiène"]', 1, 'hard'],
  ['Chimie', 'Quel est le nom de la théorie qui explique les liaisons chimiques par le recouvrement des orbitales atomiques ?', '["Théorie VSEPR", "Théorie des orbitales moléculaires", "Théorie de Lewis", "Théorie de la liaison de valence"]', 3, 'hard'],
  ['Chimie', 'Quel est le produit principal de la fermentation alcoolique du glucose par les levures ?', '["Acide lactique", "Éthanol et CO2", "Acide acétique", "Méthanol"]', 1, 'hard'],
  ['Chimie', 'Quel élément chimique, liquide à température ambiante, est un métal et a le symbole Hg ?', '["Brome", "Mercure", "Gallium", "Césium"]', 1, 'easy'],
];

export async function POST(req: Request) {
  const admin = await authenticateAdmin(req);
  if (!admin) return errorResponse('Admin access required', 403);

  try {
    const pool = getPool();
    let added = 0, skipped = 0;

    for (const [catName, question, optionsJson, correctAnswer, difficulty] of QUESTIONS) {
      const catRes = await pool.query(
        `INSERT INTO categories (name) VALUES ($1) ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id`,
        [catName]
      );
      const categoryId = catRes.rows[0].id;

      const exists = await pool.query('SELECT id FROM questions WHERE question = $1 AND category_id = $2', [question, categoryId]);
      if (exists.rows.length > 0) { skipped++; continue; }

      await pool.query(
        'INSERT INTO questions (category_id, question, options, correct_answer, difficulty, is_active) VALUES ($1, $2, $3, $4, $5, TRUE)',
        [categoryId, question, optionsJson, correctAnswer, difficulty]
      );
      added++;
    }

    const totalRes = await pool.query('SELECT COUNT(*) as c FROM questions');
    const catCounts = await pool.query('SELECT c.name, COUNT(*) as total FROM questions q JOIN categories c ON q.category_id = c.id GROUP BY c.name ORDER BY c.name');

    return successResponse({
      message: `Batch 3: Added ${added} new questions, skipped ${skipped} duplicates`,
      total_questions: Number(totalRes.rows[0].c),
      categories: catCounts.rows,
    });
  } catch (err: any) {
    return errorResponse('Seed failed: ' + err.message, 500);
  }
}
